/* Electronic documents: incoming, outgoing and internal official documents; Decree 30-style preview; workflow and digital signatures. */
(function (GA) {
  'use strict';
  const U = GA.util, t = GA.t, esc = U.esc, icon = U.icon, ui = GA.ui, S = GA.store, M = GA.mod;
  const TYPES = { CV: ['Official letter', 'CÔNG VĂN'], QĐ: ['Decision', 'QUYẾT ĐỊNH'], TB: ['Notice', 'THÔNG BÁO'], BC: ['Report', 'BÁO CÁO'], KH: ['Plan', 'KẾ HOẠCH'], GM: ['Invitation', 'GIẤY MỜI'], CT: ['Directive', 'CHỈ THỊ'], TTr: ['Submission', 'TỜ TRÌNH'] };
  const OPEN = ['Awaiting receipt', 'Processing', 'Drafting', 'Awaiting signature'];

  /* Official document facsimile following the layout conventions of Decree 30/2020/ND-CP. */
  function paper(d) {
    const org = d.direction === 'incoming' ? d.senderVi : S.setting('orgVi');
    const up = d.direction === 'incoming' ? (/^Bộ|^Văn phòng Chính phủ/.test(d.senderVi) ? '' : /phường|xã/i.test(d.senderVi) ? 'UBND QUẬN HẢI CHÂU' : 'UBND THÀNH PHỐ ĐÀ NẴNG') : '';
    const dt = new Date(d.date);
    const place = d.direction === 'incoming' && /^Bộ|Chính phủ/.test(d.senderVi) ? 'Hà Nội' : 'Đà Nẵng';
    const isCV = d.typeCode === 'CV';
    const sig = d.signature || {};
    const recips = d.direction === 'incoming' ? ['Như trên;', 'UBND thành phố Đà Nẵng;', 'Lưu: VT.'] : ['Như trên;', 'Các sở, ban, ngành;', 'UBND các phường, xã;', 'Lưu: VT, VP.'];
    return `<div class="doc-paper" aria-label="${t('Document preview')}"><div class="doc-watermark">${t('Preview · fictional document')}</div>
      <div class="doc-top"><div>${up ? `<div class="org-up">${esc(up)}</div>` : ''}<div class="org">${esc(String(org).toUpperCase())}</div><div class="rule"></div><div class="num">Số: ${esc(d.number)}</div>${isCV ? `<div class="v-sum">${esc(d.summaryVi)}</div>` : ''}</div>
        <div><div class="nation">CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM</div><div class="motto">Độc lập - Tự do - Hạnh phúc</div><div class="rule long"></div><div class="place">${place}, ngày ${String(dt.getDate()).padStart(2, '0')} tháng ${String(dt.getMonth() + 1).padStart(2, '0')} năm ${dt.getFullYear()}</div></div></div>
      ${isCV ? `<div class="mt-2" style="text-align:center">Kính gửi: ${esc(d.direction === 'incoming' ? 'Ủy ban nhân dân thành phố Đà Nẵng' : d.recipient)}</div>` : `<div class="doc-type">${esc(d.typeVi)}</div><div class="doc-summary">${esc(d.summaryVi.replace(/^(Thông báo|Kế hoạch|Báo cáo|Quyết định)\s+/i, ''))}</div><div class="rule"></div>`}
      <div class="doc-body mt-2">
        <p>Căn cứ Luật Tổ chức chính quyền địa phương và các văn bản hướng dẫn thi hành;</p>
        <p>Thực hiện chỉ đạo của cấp có thẩm quyền về ${esc(d.summaryVi.replace(/^Về việc\s*/i, '').toLowerCase())}, ${esc(org)} đề nghị các cơ quan, đơn vị liên quan quán triệt và triển khai thực hiện các nội dung sau:</p>
        <p>1. Rà soát, tổng hợp tình hình thực hiện tại đơn vị; xác định rõ nhiệm vụ, thời hạn và trách nhiệm của từng cá nhân phụ trách.</p>
        <p>2. Báo cáo kết quả thực hiện bằng văn bản điện tử qua hệ thống quản lý văn bản và điều hành trước ngày ${U.date(d.deadline || U.addDays(d.date, 10))}.</p>
        <p>Trong quá trình thực hiện, nếu có vướng mắc, đề nghị phản ánh kịp thời để được hướng dẫn, giải quyết./.</p>
      </div>
      <div class="doc-sign"><div class="recips"><b>Nơi nhận:</b><br>${recips.map((r) => '- ' + esc(r)).join('<br>')}</div>
        <div class="signer">${sig.on ? `<div>${esc(sig.on)}</div>` : ''}<div>${esc(sig.title || 'GIÁM ĐỐC')}</div>
          <div class="sig-space">${sig.status === 'Valid' ? `<div class="sig-stamp">${t('Digitally signed by')}<br>${esc(sig.signer)}<br>${U.dateTime(sig.time)}<br>${esc(sig.issuer || '')}</div>` : `<span class="xs muted" style="font-family:var(--font)">${t(sig.status === 'Pending' ? 'Awaiting digital signature' : 'Not yet signed')}</span>`}</div>
          <div>${esc(sig.signer || '')}</div></div></div></div>`;
  }

  function open(d, refresh) {
    const app = GA.app, can = app.can('edit', 'documents'), approve = app.can('approve', 'documents');
    const sig = d.signature || {};
    const acts = [{ label: t('Close') }, { label: t('Print'), left: true, icon: 'printer', onClick: () => window.print() }, { label: t('Download'), icon: 'download', onClick: () => { U.download(`${d.number.replace(/\//g, '-')}.txt`, `${d.number}\n${d.summaryVi}\n${d.summary}\n\n${t('Fictional document generated by a demo system.')}`); } }];
    const wf = (step, status, extra) => { const w = d.workflow.find((x) => !x.done); if (w) { w.done = true; w.time = U.nowIso(); w.actor = app.user.name; } S.update('documents', d.id, Object.assign({ status, workflow: d.workflow }, extra || {})); S.log(step, d.id, d.number); };
    if (can || approve) {
      if (d.status === 'Awaiting receipt') acts.push({ label: t('Receive and register'), variant: 'primary', icon: 'inbox', onClick: (m) => { wf('Registered incoming document', 'Processing', { receivedAt: U.nowIso(), regNo: d.regNo || 'Đến số ' + (4800 + S.all('documents').length) }); m.close(); ui.toast(t('Document registered in the incoming book.'), 'success'); refresh(); } });
      if (d.status === 'Processing') {
        acts.push({ label: t('Assign handler'), icon: 'user', onClick: (m) => { m.close(); ui.formModal({ title: t('Assign handler'), subtitle: esc(d.number), size: '', fields: [{ key: 'h', label: 'Handling officer', type: 'select', required: true, options: S.all('officers').map((o) => ({ value: o.id, label: `${o.name} (${ui.dept(o.dept).short})` })), default: d.handlerId }, { key: 'dl', label: 'Deadline', type: 'date', required: true, default: d.deadline || U.addDays(U.today(), 5), min: U.today() }, { key: 'note', label: 'Instructions', type: 'textarea', full: true }], submitLabel: t('Assign'), onSubmit: (v) => { S.update('documents', d.id, { handlerId: v.h, deadline: v.dl }); S.log('Assigned document', d.id, ui.officer(v.h).name); S.notify({ title: 'Document assigned to you', body: `${d.number}: ${d.summary}`, link: '#/documents?id=' + d.id }); ui.toast(t('Handler assigned.'), 'success'); refresh(); } }); } });
        acts.push({ label: t('Mark as completed'), variant: 'success', icon: 'check', onClick: (m) => { wf('Completed document processing', 'Completed', { deadline: '' }); m.close(); ui.toast(t('Processing completed.'), 'success'); refresh(); } });
      }
      if (d.status === 'Drafting') acts.push({ label: t('Submit for signature'), variant: 'primary', icon: 'send', onClick: (m) => { d.signature.status = 'Pending'; wf('Submitted document for signature', 'Awaiting signature', { signature: d.signature }); m.close(); S.notify({ title: 'Document awaiting your signature', body: `${d.number}: ${d.summary}`, type: 'warning', link: '#/documents?id=' + d.id }); ui.toast(t('Sent to the signer.'), 'success'); refresh(); } });
      if (d.status === 'Awaiting signature') acts.push(approve ? { label: t('Sign digitally'), variant: 'primary', icon: 'pen', onClick: (m) => { m.close(); signFlow(d, refresh); } } : { label: t('Waiting for leadership signature'), onClick: () => ui.toast(t('Only department leadership can sign. Switch to the Department Manager role to try it.'), 'info') });
      if (d.status === 'Signed') acts.push({ label: t('Issue and send'), variant: 'primary', icon: 'send', onClick: (m) => { wf('Issued document', 'Issued', { deadline: '' }); m.close(); ui.toast(t('Issued to {r} via the inter-agency document exchange.', { r: esc(d.recipient) }), 'success'); refresh(); } });
      if (['Completed', 'Issued'].includes(d.status)) acts.push({ label: t('Archive'), icon: 'database', onClick: (m) => { d.workflow.forEach((w) => { if (!w.done) { w.done = true; w.time = U.nowIso(); w.actor = app.user.name; } }); S.update('documents', d.id, { status: 'Archived', workflow: d.workflow }); S.log('Archived document', d.id, d.number); m.close(); ui.toast(t('Document archived.'), 'success'); refresh(); } });
    }
    const meta = `<div class="doc-meta">
      <div class="flex flex-wrap mb-1">${ui.badge(d.status)} ${ui.priority(d.priority)} ${d.confidential !== 'Normal' ? ui.badge('Locked', 'Restricted') : ''}</div>
      ${ui.dl([['Number and symbol', `<span class="code strong">${esc(d.number)}</span>`], ['Document type', `${t(d.type)} (${esc(d.typeCode)})`], ['Summary', esc(t(d.summary))], [d.direction === 'incoming' ? 'Issuing authority' : 'Recipient', esc(d.direction === 'incoming' ? t(d.sender) : d.recipient)], ['Date issued', U.date(d.date)], d.direction === 'incoming' ? ['Received', `${U.dateTime(d.receivedAt)}${d.regNo ? `<span class="sub">${esc(d.regNo)}</span>` : ''}`] : null, ['Handler', ui.officerName(d.handlerId)], ['Deadline', d.deadline ? U.deadline(d.deadline) : '—'], ['Pages', d.pages], ['Attachments', d.attachments ? `${d.attachments} ${t('files')}` : '—']])}
      <div class="form-section-title">${t('Digital signature')}</div>
      <div class="sig-box"><span class="l-ic ${sig.status === 'Valid' ? 'ok' : 'warn'}">${icon(sig.status === 'Valid' ? 'shield' : 'pen')}</span><div>${sig.status === 'Valid' ? `<div class="strong">${t('Signature valid')}</div><div class="small">${esc(sig.signer)}, ${esc(sig.title)}</div><div class="xs muted">${t('Certificate')} <span class="code">${esc(sig.cert)}</span> · ${esc(sig.issuer)}<br>${t('Signed at')} ${U.dateTime(sig.time)}</div>` : `<div class="strong">${t(sig.status === 'Pending' ? 'Awaiting signature' : 'Not signed')}</div><div class="small">${t('Signer')}: ${esc(sig.signer || '—')}, ${esc(sig.title || '')}</div>`}</div></div>
      <div class="form-section-title">${t('Processing workflow')}</div>
      ${ui.timeline(d.workflow.map((w) => ({ title: esc(t(w.step)), meta: w.done ? `${esc(w.actor || '')} · ${U.dateTime(w.time)}` : t('Pending'), tone: w.done ? 'ok' : '' })))}
    </div>`;
    ui.modal({ title: esc(d.number), subtitle: esc(t(d.summary)), size: 'xl', flush: true, body: `<div class="doc-view"><div class="doc-canvas">${paper(d)}</div>${meta}</div>`, actions: acts });
  }

  function signFlow(d, refresh) {
    const app = GA.app;
    const m = ui.modal({ title: t('Sign document digitally'), subtitle: esc(d.number), size: '',
      body: `<div class="callout mb-2">${icon('shield')}<div>${t('Signing with the government specialised digital certificate (remote signing, demo). The signature image and time stamp are embedded in the PDF.')}</div></div>
        ${ui.dl([['Signer', esc(app.user.name)], ['Position', esc(app.user.title)], ['Certificate', '<span class="code">CA-' + String(Date.now()).slice(-12) + '</span>'], ['Provider', t('Government Specialised CA (demo)')]])}
        <div class="field mt-2" data-field="otp"><label for="sg-otp">${t('One-time passcode sent to your phone')}<span class="req">*</span></label><input id="sg-otp" inputmode="numeric" maxlength="6" placeholder="6 ${t('digits')}"><div class="help">${t('Demo: any 6 digits are accepted.')}</div><div class="err">${t('Enter the 6-digit passcode.')}</div></div>`,
      actions: [{ label: t('Cancel') }, { label: t('Sign'), variant: 'primary', icon: 'pen', onClick: (mm) => {
        const v = U.$('#sg-otp', mm.el).value.trim();
        if (!/^\d{6}$/.test(v)) { U.$('[data-field=otp]', mm.el).classList.add('invalid'); return; }
        const w = d.workflow.find((x) => !x.done); if (w) { w.done = true; w.time = U.nowIso(); w.actor = app.user.name; }
        const sig = { status: 'Valid', signer: app.user.name, title: String(app.user.title || '').toUpperCase(), on: d.signature.on || '', time: U.nowIso(), cert: 'CA-' + String(Date.now()).slice(-4) + '-' + String(Date.now()).slice(-8), issuer: 'Government Specialised CA (demo)' };
        S.update('documents', d.id, { status: 'Signed', signature: sig, workflow: d.workflow }); S.log('Signed document digitally', d.id, d.number);
        mm.close(); ui.toast(t('Document signed. Signature verified.'), 'success'); refresh(); setTimeout(() => open(S.find('documents', d.id), refresh), 50);
      } }] });
    void m;
  }

  function create(dir, refresh) {
    const incoming = dir === 'incoming';
    const fields = [
      { key: 'typeCode', label: 'Document type', type: 'select', required: true, options: Object.keys(TYPES).map((k) => ({ value: k, label: `${k} · ${t(TYPES[k][0])}` })) },
      { key: 'number', label: incoming ? 'Number and symbol (as printed)' : 'Number and symbol', required: true, placeholder: incoming ? 'e.g. 1234/BTC-QLCS' : 'Issued automatically when left blank', default: incoming ? '' : `${S.all('documents').length + 400}/UBND-VP`, validate: (v) => (!/^\d+\/[A-ZĐa-z0-9-]+$/.test(v) ? t('Use the format number/SYMBOL, e.g. 1234/UBND-VP.') : '') },
      incoming ? { key: 'sender', label: 'Issuing authority', required: true } : { key: 'recipient', label: 'Recipient', required: true, default: "Departments, agencies and ward People's Committees" },
      { key: 'date', label: 'Date issued', type: 'date', required: true, default: U.today(), max: U.today() },
      { key: 'priority', label: 'Priority', type: 'select', required: true, noBlank: true, options: ['Normal', 'Urgent', 'Very urgent'] },
      { key: 'handlerId', label: incoming ? 'Handler' : 'Drafting officer', type: 'select', required: true, options: S.all('officers').map((o) => ({ value: o.id, label: `${o.name} (${ui.dept(o.dept).short})` })), default: GA.app.officerId() },
      { key: 'summary', label: 'Summary (English)', required: true, full: true },
      { key: 'summaryVi', label: 'Trích yếu (Vietnamese summary)', required: true, full: true, placeholder: 'Về việc …' },
      { key: 'pages', label: 'Pages', type: 'number', min: 1, default: 1 },
      { key: 'signer', label: 'Signer', type: 'select', noBlank: true, options: ['Phạm Văn Thành', 'Lê Thị Minh Tâm', 'Hồ Quang Huy', 'Nguyễn Đình Khang'] },
    ];
    ui.formModal({ title: t(incoming ? 'Register incoming document' : dir === 'internal' ? 'Draft internal document' : 'Draft outgoing document'), size: 'xl', fields, submitLabel: t(incoming ? 'Register' : 'Save draft'),
      onSubmit: (v) => {
        if (S.all('documents').some((x) => x.number === v.number)) { ui.toast(t('A document with this number already exists.'), 'error'); return false; }
        const pr = v.priority, dl = U.addDays(v.date, pr === 'Very urgent' ? 1 : pr === 'Urgent' ? 3 : 10);
        const me = GA.app.user.name;
        const rec = { id: S.nextId('documents', 'DOC-'), direction: dir, type: TYPES[v.typeCode][0], typeCode: v.typeCode, typeVi: TYPES[v.typeCode][1], number: v.number, regNo: incoming ? 'Đến số ' + (4800 + S.all('documents').length) : '', summary: v.summary, summaryVi: v.summaryVi, sender: incoming ? v.sender : S.setting('orgName'), senderVi: incoming ? v.sender : S.setting('orgVi'), recipient: incoming ? "City People's Committee" : v.recipient, date: v.date, receivedAt: incoming ? U.nowIso() : '', priority: pr, status: incoming ? 'Processing' : 'Drafting', deadline: dl, handlerId: v.handlerId, pages: v.pages || 1, confidential: 'Normal',
          signature: incoming ? { status: 'Valid', signer: v.sender, title: '', on: '', time: v.date + 'T08:00:00.000Z', cert: 'external', issuer: 'Issuing authority certificate (demo)' } : { status: 'Unsigned', signer: v.signer, title: 'PHÓ CHỦ TỊCH', on: 'KT. CHỦ TỊCH' },
          workflow: incoming ? [{ step: 'Received and registered', actor: me, time: U.nowIso(), done: true }, { step: 'Assigned by leadership', actor: '', time: '', done: false }, { step: 'Processed by specialist', actor: '', time: '', done: false }, { step: 'Filed', actor: '', time: '', done: false }]
            : [{ step: 'Drafted by specialist', actor: me, time: U.nowIso(), done: true }, { step: 'Reviewed by division head', actor: '', time: '', done: false }, { step: 'Signed digitally', actor: '', time: '', done: false }, { step: 'Issued and sent', actor: '', time: '', done: false }, { step: 'Filed', actor: '', time: '', done: false }], attachments: 0, createdAt: U.nowIso() };
        S.insert('documents', rec); S.log(incoming ? 'Registered incoming document' : 'Drafted document', rec.id, rec.number); ui.toast(t('Document {n} saved.', { n: esc(rec.number) }), 'success'); refresh();
      } });
  }

  function render(el, params, q) {
    const app = GA.app, can = app.can('edit', 'documents');
    const all = S.all('documents');
    let tab = q.tab || 'incoming';
    const refresh = () => render(el, params, { tab });
    const cnt = (dir) => all.filter((d) => d.direction === dir).length;
    el.innerHTML = `${ui.pageHeader({ crumbs: [{ label: t('Home'), href: '#/dashboard' }, { label: t('Electronic documents') }], title: t('Electronic documents'), subtitle: t('Document management and executive system · incoming, outgoing and internal documents'),
      actions: can ? `<div class="dd"><button class="btn btn-primary" data-dd-toggle aria-haspopup="true" aria-expanded="false">${icon('plus')}${t('New document')}${icon('chevD', 'i-sm')}</button><div class="dd-menu"><button class="dd-item" data-new="incoming">${icon('inbox')}${t('Register incoming document')}</button><button class="dd-item" data-new="outgoing">${icon('send')}${t('Draft outgoing document')}</button><button class="dd-item" data-new="internal">${icon('file')}${t('Draft internal document')}</button></div></div>` : '' })}
      ${ui.kpis([
        { label: 'Incoming this year (city)', value: U.num(S.state.stats.docsIncomingYtd), meta: `${all.filter((d) => d.status === 'Awaiting receipt').length} ${t('awaiting receipt')}`, icon: 'inbox' },
        { label: 'In progress', value: all.filter((d) => OPEN.includes(d.status)).length, meta: `${all.filter((d) => OPEN.includes(d.status) && d.deadline && d.deadline < U.today()).length} ${t('overdue')}`, icon: 'clock', color: 'var(--gold)' },
        { label: 'Awaiting signature', value: all.filter((d) => d.status === 'Awaiting signature').length, icon: 'pen', color: 'var(--red)' },
        { label: 'Digitally signed', value: U.pct(all.filter((d) => d.signature && d.signature.status === 'Valid').length, all.length) + '%', meta: t('of documents in register'), icon: 'shield', color: 'var(--ok)' },
      ], 'compact')}
      ${ui.tabs(['incoming', 'outgoing', 'internal'].map((dir) => ({ id: dir, label: { incoming: 'Incoming', outgoing: 'Outgoing', internal: 'Internal' }[dir], icon: { incoming: 'inbox', outgoing: 'send', internal: 'file' }[dir], count: cnt(dir), content: `<div class="panel"><div class="panel-body flush" id="dc-${dir}"></div></div>` })), { cls: 'page-tabs', active: tab, id: 'dctabs' })}`;
    ['incoming', 'outgoing', 'internal'].forEach((dir) => ui.table(U.$('#dc-' + dir, el), {
      rows: () => S.where('documents', (d) => d.direction === dir), exportName: 'documents-' + dir,
      searchKeys: ['number', 'summary', 'summaryVi', 'sender', 'recipient', 'regNo'], searchPlaceholder: t('Search by number, summary or authority'),
      filters: [{ key: 'typeCode', label: 'Type', all: 'All types', options: Object.keys(TYPES).map((k) => ({ value: k, label: t(TYPES[k][0]) })) }, { key: 'priority', label: 'Priority', all: 'All priorities', options: ['Normal', 'Urgent', 'Very urgent'] }, { key: 'status', label: 'Status', all: 'All statuses', options: dir === 'incoming' ? ['Awaiting receipt', 'Processing', 'Completed', 'Archived'] : ['Drafting', 'Awaiting signature', 'Signed', 'Issued', 'Archived'] }],
      dateKey: 'date', dateLabel: 'Issued from', defaultSort: 'date',
      columns: [
        { key: 'number', label: 'Number', render: (d) => `<span class="strong code">${esc(d.number)}</span><span class="sub">${t(d.type)}</span>` },
        { key: 'summary', label: 'Summary', render: (d) => `${esc(t(d.summary))}<span class="sub">${esc(d.summaryVi)}</span>` },
        dir === 'incoming' ? { key: 'sender', label: 'Issuing authority', render: (d) => esc(t(d.sender)) } : { key: 'recipient', label: 'Recipient', render: (d) => `<span class="small">${esc(d.recipient)}</span>` },
        { key: 'date', label: 'Date', render: (d) => U.date(d.date) },
        { key: 'priority', label: 'Priority', sort: (d) => ['Normal', 'Urgent', 'Very urgent'].indexOf(d.priority), render: (d) => ui.priority(d.priority) },
        { key: 'deadline', label: 'Deadline', render: (d) => (d.deadline && OPEN.includes(d.status) ? U.deadline(d.deadline) : '—'), csv: (d) => U.date(d.deadline) },
        { key: 'sig', label: 'Signature', sort: (d) => (d.signature || {}).status, render: (d) => ui.badge((d.signature || {}).status === 'Valid' ? 'Signed' : (d.signature || {}).status === 'Pending' ? 'Pending' : 'Unsigned', (d.signature || {}).status === 'Valid' ? 'Signed' : (d.signature || {}).status === 'Pending' ? 'Pending' : 'Unsigned'), csv: (d) => (d.signature || {}).status },
        { key: 'status', label: 'Status', render: (d) => ui.badge(d.status) },
      ],
      onRowClick: (d) => open(d, refresh), rowActions: () => [{ id: 'o', label: 'Open document', icon: 'eye' }], onAction: (id, d) => open(d, refresh),
    }));
    U.$$('[data-new]', el).forEach((b) => b.onclick = () => create(b.dataset.new, refresh));
    ui.bindTabs(el, (id) => { tab = id; });
    if (q.id) { const d = S.find('documents', q.id); if (d) { const b = U.$(`[data-tab=${d.direction}]`, el); if (b) b.click(); setTimeout(() => { M.clearQuery(); open(d, refresh); }, 40); } }
  }

  GA.modules.documents = { render };
})(window.GA);
