/* EnglishUp — mock data (no backend) */
'use strict';
const DATA = {};

DATA.levels = { A1: 'Beginner', A2: 'Elementary', B1: 'Intermediate', B2: 'Upper Intermediate', C1: 'Advanced', C2: 'Proficient' };

/* ---------------- Courses ---------------- */
DATA.categories = ['General English', 'Communication', 'Professional English', 'Exam Preparation'];
DATA.courses = [
  { id: 'c1', title: 'Beginner English', category: 'General English', level: 'A1', duration: '6h 40m', rating: 4.8, students: 15420, price: 0, emoji: '🌱', hue: 145, teacher: 't3', tags: ['daily'],
    desc: 'Start from zero with greetings, numbers and simple sentences. Every lesson has Vietnamese support.',
    outcomes: ['Introduce yourself confidently', 'Use 300+ everyday words', 'Understand slow, simple conversations', 'Pronounce basic English sounds'],
    syllabus: ['The English Alphabet & Sounds', 'Greetings and Introductions', 'Numbers, Dates and Time', 'My Family', 'Daily Routines', 'Food and Drinks'] },
  { id: 'c2', title: 'Elementary English', category: 'General English', level: 'A2', duration: '7h 10m', rating: 4.7, students: 11230, price: 149000, emoji: '📗', hue: 160, teacher: 't9', tags: ['daily', 'emotions'],
    desc: 'Build everyday sentences, the past simple and basic questions so you can handle simple daily situations.',
    outcomes: ['Talk about your past weekend', 'Ask and answer common questions', 'Describe feelings', 'Write short messages'],
    syllabus: ['Talking About Yesterday', 'Asking Questions', 'Describing Feelings', 'Likes and Dislikes', 'Making Simple Plans', 'Writing a Short Message'] },
  { id: 'c3', title: 'English Communication — Intermediate', category: 'General English', level: 'B1', duration: '5h 30m', rating: 4.9, students: 21870, price: 199000, emoji: '💬', hue: 230, teacher: 't1', tags: ['daily'],
    desc: 'Speak fluently about experiences, opinions and stories. Designed for learners who understand English but freeze when speaking.',
    outcomes: ['Share opinions politely', 'Tell stories in the past', 'Agree and disagree naturally', 'Use the present perfect correctly'] },
  { id: 'c4', title: 'Advanced English', category: 'General English', level: 'C1', duration: '8h 00m', rating: 4.8, students: 5210, price: 299000, emoji: '🎓', hue: 265, teacher: 't2', tags: ['ielts'],
    desc: 'Nuance, idioms and complex structures for learners who want to sound precise and natural.',
    outcomes: ['Use idioms appropriately', 'Master inversion and cleft sentences', 'Debate complex topics', 'Write with a natural academic tone'],
    syllabus: ['Idioms in Context', 'Inversion for Emphasis', 'Cleft Sentences', 'Hedging Language', 'Debating Skills', 'Advanced Collocations'] },
  { id: 'c5', title: 'Daily Conversation', category: 'Communication', level: 'A2', duration: '4h 50m', rating: 4.9, students: 28400, price: 0, emoji: '☕', hue: 30, teacher: 't5', tags: ['daily', 'travel'],
    desc: 'Short, practical conversations you use every day: coffee, shopping, directions and phone calls.',
    outcomes: ['Order food and drinks', 'Ask for directions', 'Make plans with friends', 'Handle phone calls'] },
  { id: 'c6', title: 'Travel English', category: 'Communication', level: 'A2', duration: '4h 20m', rating: 4.8, students: 13200, price: 149000, emoji: '✈️', hue: 195, teacher: 't5', tags: ['travel'],
    desc: 'Airports, hotels, restaurants and emergencies — everything for your next trip abroad.',
    outcomes: ['Check in at the airport', 'Book and complain about hotels', 'Order at restaurants', 'Ask for help'],
    syllabus: ['At the Airport', 'Hotel Check-in', 'Getting Around the City', 'Eating Out', 'Shopping for Souvenirs', 'Handling Problems'] },
  { id: 'c7', title: 'English at Work', category: 'Communication', level: 'B1', duration: '5h 10m', rating: 4.7, students: 9870, price: 199000, emoji: '💼', hue: 215, teacher: 't4', tags: ['work'],
    desc: 'Emails, small talk with colleagues and asking for help in a professional environment.',
    outcomes: ['Write clear work emails', 'Make small talk with colleagues', 'Ask for and give help', 'Report progress'],
    syllabus: ['Small Talk at the Office', 'Writing Professional Emails', 'Asking for Help', 'Giving Updates', 'Handling Requests', 'Workplace Culture'] },
  { id: 'c8', title: 'Meeting English', category: 'Communication', level: 'B1', duration: '3h 40m', rating: 4.6, students: 6120, price: 199000, emoji: '🗓️', hue: 250, teacher: 't4', tags: ['work'],
    desc: 'Lead and join meetings: agendas, interrupting politely, summarising and action items.',
    outcomes: ['Open and close meetings', 'Interrupt politely', 'Summarise decisions', 'Assign action items'],
    syllabus: ['Opening a Meeting', 'Sharing Your View', 'Interrupting Politely', 'Handling Disagreement', 'Summarising Decisions', 'Following Up'] },
  { id: 'c9', title: 'Presentation English', category: 'Communication', level: 'B2', duration: '4h 00m', rating: 4.8, students: 5480, price: 249000, emoji: '🎤', hue: 290, teacher: 't7', tags: ['work'],
    desc: 'Structure, signposting and Q&A for presentations that sound confident.',
    outcomes: ['Open with impact', 'Use signposting language', 'Describe charts', 'Handle tough questions'],
    syllabus: ['Strong Openings', 'Signposting Language', 'Describing Data', 'Storytelling', 'Handling Q&A', 'Closing with Impact'] },
  { id: 'c10', title: 'IT English', category: 'Professional English', level: 'B1', duration: '4h 30m', rating: 4.7, students: 7340, price: 199000, emoji: '🖥️', hue: 205, teacher: 't6', tags: ['tech'],
    desc: 'Core technology vocabulary for support, operations and IT communication.',
    outcomes: ['Describe systems and issues', 'Write support tickets', 'Explain technical steps', 'Talk about security'],
    syllabus: ['Hardware and Software', 'Writing Support Tickets', 'Explaining Steps', 'Networks and Security', 'Cloud Basics', 'Incident Reports'] },
  { id: 'c11', title: 'English for Developers', category: 'Professional English', level: 'B1', duration: '4h 45m', rating: 4.9, students: 12650, price: 249000, emoji: '👩‍💻', hue: 175, teacher: 't6', tags: ['tech', 'work'],
    desc: 'Stand-ups, bug reports, code reviews and client calls — English that Vietnamese developers use every day.',
    outcomes: ['Give clear stand-up updates', 'Explain bugs precisely', 'Write professional PR descriptions', 'Discuss estimates with clients'] },
  { id: 'c12', title: 'Business English', category: 'Professional English', level: 'B2', duration: '6h 00m', rating: 4.8, students: 8910, price: 299000, emoji: '📈', hue: 220, teacher: 't2', tags: ['work'],
    desc: 'Negotiation, reports and professional communication with international partners.',
    outcomes: ['Negotiate confidently', 'Write reports', 'Talk about numbers and trends', 'Build business relationships'],
    syllabus: ['Building Relationships', 'Negotiation Basics', 'Talking About Numbers', 'Writing Reports', 'Making Proposals', 'Closing a Deal'] },
  { id: 'c13', title: 'Technical English', category: 'Professional English', level: 'B2', duration: '4h 10m', rating: 4.6, students: 3920, price: 249000, emoji: '⚙️', hue: 185, teacher: 't10', tags: ['tech'],
    desc: 'Documentation, specifications and technical writing for engineers.',
    outcomes: ['Read documentation faster', 'Write specifications', 'Describe processes', 'Use passive voice in reports'],
    syllabus: ['Reading Documentation', 'Writing Specifications', 'Describing Processes', 'Passive Voice in Reports', 'Architecture Discussions', 'Technical Q&A'] },
  { id: 'c14', title: 'Interview English', category: 'Professional English', level: 'B1', duration: '4h 15m', rating: 4.9, students: 16780, price: 199000, emoji: '🤝', hue: 340, teacher: 't8', tags: ['work'],
    desc: 'Prepare real answers for English job interviews, from "Tell me about yourself" to salary talks.',
    outcomes: ['Introduce yourself professionally', 'Answer with the STAR method', 'Talk about salary', 'Ask smart questions'] },
  { id: 'c15', title: 'IELTS Preparation', category: 'Exam Preparation', level: 'B2', duration: '9h 30m', rating: 4.9, students: 19350, price: 399000, emoji: '🏅', hue: 265, teacher: 't2', tags: ['ielts'],
    desc: 'Strategies and practice for all four IELTS skills, targeting band 6.5–7.5.',
    outcomes: ['Know every IELTS task type', 'Describe charts in Task 1', 'Write clear opinion essays', 'Speak fluently in Part 2'] },
  { id: 'c16', title: 'TOEIC 750+', category: 'Exam Preparation', level: 'B1', duration: '7h 20m', rating: 4.7, students: 14120, price: 299000, emoji: '📝', hue: 25, teacher: 't9', tags: ['work'],
    desc: 'Listening and reading strategies with timed practice for the TOEIC test.',
    outcomes: ['Master Part 1–7 strategies', 'Build business vocabulary', 'Manage time', 'Avoid common traps'],
    syllabus: ['TOEIC Overview', 'Photographs & Question-Response', 'Conversations & Talks', 'Incomplete Sentences', 'Text Completion', 'Reading Comprehension'] },
  { id: 'c17', title: 'TOEFL iBT Essentials', category: 'Exam Preparation', level: 'B2', duration: '6h 50m', rating: 4.6, students: 3210, price: 349000, emoji: '🎯', hue: 0, teacher: 't7', tags: ['ielts'],
    desc: 'Academic reading, lectures and integrated tasks for TOEFL iBT.',
    outcomes: ['Take notes on lectures', 'Answer integrated tasks', 'Read academic texts', 'Speak with structure'],
    syllabus: ['TOEFL Overview', 'Academic Reading', 'Lecture Note-taking', 'Independent Speaking', 'Integrated Writing', 'Test-day Strategy'] }
];

/* ---------------- Lessons (30 detailed) ---------------- */
const mk = (course, n, title, duration, script, vocab, en, vi, examples, practice) =>
  ({ id: `${course}-${n}`, course, n, title, duration, script, vocab, explain: { en, vi }, examples, practice });

DATA.lessons = [
  /* c3 — English Communication Intermediate */
  mk('c3', 1, 'Talking About Experiences', '12 min', 'Have you ever eaten durian? Today we will learn how to talk about life experiences using the present perfect.',
    [['experience', '/ɪkˈspɪəriəns/', 'trải nghiệm'], ['ever', '/ˈevər/', 'từng (bao giờ)'], ['recently', '/ˈriːsntli/', 'gần đây']],
    'Use "Have you ever…?" to ask about life experiences. Answer with "Yes, I have" or "No, I haven\'t".',
    'Dùng thì hiện tại hoàn thành để nói về trải nghiệm trong đời mà không nói thời điểm cụ thể.',
    [['Have you ever been to Japan?', 'Bạn đã từng đến Nhật chưa?'], ['I have tried scuba diving twice.', 'Tôi đã thử lặn biển hai lần.'], ["I've never seen snow.", 'Tôi chưa bao giờ thấy tuyết.']],
    [{ q: 'She ____ to Singapore three times.', options: ['goes', 'has been', 'is going', 'go'], answer: 1, vi: '"Three times" chỉ số lần trải nghiệm → hiện tại hoàn thành.' },
     { q: 'Have you ever ____ sushi?', options: ['eat', 'ate', 'eaten', 'eating'], answer: 2, vi: 'Sau "have" dùng quá khứ phân từ (V3): eaten.' }]),
  mk('c3', 2, 'Giving Opinions Politely', '10 min', 'In my opinion, being polite is the key to good conversations. Let us learn soft ways to share your view.',
    [['opinion', '/əˈpɪnjən/', 'ý kiến'], ['perspective', '/pəˈspektɪv/', 'góc nhìn'], ['honestly', '/ˈɒnɪstli/', 'thật lòng mà nói']],
    'Soften opinions with "I think", "In my view", or "It seems to me that". Avoid "In my opinion, I think" (repetition).',
    'Người bản xứ thường làm mềm ý kiến. Tránh nói "In my opinion, I think" vì bị lặp ý.',
    [['In my view, remote work is more productive.', 'Theo tôi, làm việc từ xa hiệu quả hơn.'], ['It seems to me that the price is too high.', 'Tôi thấy giá hơi cao.'], ['I might be wrong, but I think we need more time.', 'Có thể tôi sai, nhưng tôi nghĩ chúng ta cần thêm thời gian.']],
    [{ q: 'Which sentence is the most natural?', options: ['In my opinion, I think it is good.', 'I think it is good.', 'I am think it is good.', 'My opinion think it good.'], answer: 1, vi: 'Chỉ cần "I think" hoặc "In my opinion", không dùng cả hai.' },
     { q: '"____ me, the movie was too long."', options: ['For', 'To', 'With', 'At'], answer: 0, vi: '"For me" = đối với tôi.' }]),
  mk('c3', 3, 'Making Suggestions', '11 min', 'Why don\'t we practise together? Suggestions help you plan and solve problems with other people.',
    [['suggest', '/səˈdʒest/', 'đề xuất'], ['instead', '/ɪnˈsted/', 'thay vào đó'], ['option', '/ˈɒpʃn/', 'lựa chọn']],
    'Use "How about + V-ing", "Why don\'t we + V", or "Let\'s + V". After "suggest", use V-ing or "that + clause".',
    'Sau "suggest" không dùng "to V". Nói "I suggest going" hoặc "I suggest that we go".',
    [['How about taking a taxi?', 'Hay là mình đi taxi nhé?'], ["Why don't we meet on Friday?", 'Sao mình không gặp vào thứ Sáu?'], ['I suggest starting earlier.', 'Tôi đề xuất bắt đầu sớm hơn.']],
    [{ q: 'I suggest ____ the meeting.', options: ['to postpone', 'postponing', 'postpone', 'postponed'], answer: 1, vi: 'suggest + V-ing.' },
     { q: 'How about ____ pho for lunch?', options: ['have', 'to have', 'having', 'had'], answer: 2, vi: 'How about + V-ing.' }]),
  mk('c3', 4, 'Describing People & Places', '12 min', 'Hoi An is a charming old town with friendly people. Let us describe people and places with rich adjectives.',
    [['charming', '/ˈtʃɑːmɪŋ/', 'duyên dáng, quyến rũ'], ['crowded', '/ˈkraʊdɪd/', 'đông đúc'], ['easy-going', '/ˌiːzi ˈɡəʊɪŋ/', 'dễ tính']],
    'Order adjectives: opinion → size → age → colour → origin. Example: a lovely small old Vietnamese house.',
    'Thứ tự tính từ: ý kiến → kích thước → tuổi → màu sắc → nguồn gốc.',
    [['My manager is easy-going and supportive.', 'Quản lý của tôi dễ tính và hay giúp đỡ.'], ['Da Nang is a clean, modern city.', 'Đà Nẵng là một thành phố sạch sẽ, hiện đại.'], ['The market is always crowded at weekends.', 'Chợ luôn đông đúc vào cuối tuần.']],
    [{ q: 'Choose the correct order:', options: ['a red beautiful dress', 'a beautiful red dress', 'a dress beautiful red', 'red a beautiful dress'], answer: 1, vi: 'Ý kiến (beautiful) đứng trước màu sắc (red).' },
     { q: 'Someone who stays calm and relaxed is ____.', options: ['crowded', 'easy-going', 'charming', 'strict'], answer: 1, vi: 'easy-going = dễ tính, thoải mái.' }]),
  mk('c3', 5, 'Telling a Story in the Past', '14 min', 'Last summer, while I was walking on the beach, I found a message in a bottle. Stories use the past simple and past continuous.',
    [['suddenly', '/ˈsʌdənli/', 'đột nhiên'], ['while', '/waɪl/', 'trong khi'], ['eventually', '/ɪˈventʃuəli/', 'cuối cùng']],
    'Use the past continuous for the background (was walking) and the past simple for the main event (found).',
    'Quá khứ tiếp diễn diễn tả hành động đang xảy ra, quá khứ đơn diễn tả hành động xen vào.',
    [['I was cooking when the phone rang.', 'Tôi đang nấu ăn thì điện thoại reo.'], ['Suddenly, the lights went out.', 'Đột nhiên đèn tắt.'], ['Eventually, we found the hotel.', 'Cuối cùng chúng tôi cũng tìm được khách sạn.']],
    [{ q: 'While I ____ TV, my friend called.', options: ['watched', 'was watching', 'am watching', 'watch'], answer: 1, vi: 'Hành động đang diễn ra → quá khứ tiếp diễn.' },
     { q: 'Which word means "cuối cùng"?', options: ['suddenly', 'while', 'eventually', 'recently'], answer: 2, vi: 'eventually = cuối cùng (sau một thời gian).' }]),
  mk('c3', 6, 'Agreeing and Disagreeing', '10 min', 'I see your point, but I have a different idea. Learn to agree and disagree without sounding rude.',
    [['point', '/pɔɪnt/', 'luận điểm'], ['exactly', '/ɪɡˈzæktli/', 'chính xác'], ['disagree', '/ˌdɪsəˈɡriː/', 'không đồng ý']],
    'Agree: "Exactly!", "I couldn\'t agree more." Disagree softly: "I see your point, but…". Never say "I am agree".',
    '"Agree" là động từ, không dùng "I am agree". Nói "I agree".',
    [["I couldn't agree more.", 'Tôi hoàn toàn đồng ý.'], ['I see your point, but I think it is risky.', 'Tôi hiểu ý bạn, nhưng tôi nghĩ nó rủi ro.'], ["I'm not sure about that.", 'Tôi không chắc về điều đó.']],
    [{ q: 'Which is correct?', options: ['I am agree with you.', 'I agree with you.', 'I agreeing you.', 'I am agreed you.'], answer: 1, vi: '"Agree" là động từ thường.' },
     { q: 'A polite way to disagree:', options: ["You're wrong.", 'No way.', 'I see your point, but…', 'That is stupid.'], answer: 2, vi: 'Công nhận ý kiến người khác trước khi phản biện.' }]),

  /* c5 — Daily Conversation */
  mk('c5', 1, 'Greetings & Small Talk', '8 min', 'Hi, how is it going? Small talk helps you start conversations with anyone.',
    [['small talk', '/ˈsmɔːl tɔːk/', 'nói chuyện xã giao'], ['weather', '/ˈweðər/', 'thời tiết'], ['catch up', '/kætʃ ʌp/', 'hàn huyên']],
    'Reply to "How\'s it going?" with "Pretty good, thanks. You?" rather than a long answer.',
    'Câu hỏi thăm xã giao chỉ cần trả lời ngắn gọn rồi hỏi lại.',
    [["How's it going?", 'Dạo này thế nào?'], ['Lovely weather today, isn\'t it?', 'Hôm nay trời đẹp nhỉ?'], ["Let's catch up soon!", 'Sớm gặp lại hàn huyên nhé!']],
    [{ q: '"How\'s it going?" — best reply:', options: ['I am going to school.', 'Pretty good, thanks. You?', 'It goes.', 'Yes, it is.'], answer: 1, vi: 'Trả lời ngắn và hỏi lại.' },
     { q: '"Catch up" means:', options: ['đuổi theo xe', 'hàn huyên, cập nhật tin tức', 'bắt bóng', 'thức khuya'], answer: 1, vi: 'catch up (with someone) = trò chuyện cập nhật tình hình.' }]),
  mk('c5', 2, 'Ordering Food & Drinks', '9 min', 'I would like a medium iced latte, please. Let us order food and drinks politely.',
    [['medium', '/ˈmiːdiəm/', 'cỡ vừa'], ['to go', '/tə ɡəʊ/', 'mang đi'], ['recommend', '/ˌrekəˈmend/', 'gợi ý']],
    'Use "I\'d like…" or "Can I get…?" to order. "For here or to go?" asks if you eat in or take away.',
    '"I\'d like" lịch sự hơn "I want" khi gọi món.',
    [["I'd like a medium coffee, please.", 'Cho tôi một ly cà phê cỡ vừa.'], ['Can I get the bill, please?', 'Cho tôi xin hoá đơn.'], ['What do you recommend?', 'Bạn gợi ý món gì?']],
    [{ q: 'Most polite way to order:', options: ['Give me coffee.', 'I want coffee now.', "I'd like a coffee, please.", 'Coffee!'], answer: 2, vi: '"I\'d like… please" là lịch sự nhất.' },
     { q: '"To go" means:', options: ['ăn tại chỗ', 'mang đi', 'đi về', 'đi bộ'], answer: 1, vi: '"to go" = mang đi (take away).' }]),
  mk('c5', 3, 'Shopping & Prices', '9 min', 'How much is this shirt? Do you have it in a larger size? Let us go shopping in English.',
    [['discount', '/ˈdɪskaʊnt/', 'giảm giá'], ['try on', '/traɪ ɒn/', 'mặc thử'], ['receipt', '/rɪˈsiːt/', 'hoá đơn']],
    'Use "How much is/are…?" for prices. "Can I try it on?" to try clothes. Note: "receipt" has a silent "p".',
    'Chữ "p" trong "receipt" là âm câm, đọc /rɪˈsiːt/.',
    [['How much are these shoes?', 'Đôi giày này bao nhiêu tiền?'], ['Can I try this on?', 'Tôi mặc thử được không?'], ['Is there a discount for students?', 'Có giảm giá cho sinh viên không?']],
    [{ q: 'How much ____ these jeans?', options: ['is', 'are', 'be', 'does'], answer: 1, vi: '"Jeans" luôn ở dạng số nhiều → are.' },
     { q: 'Which letter is silent in "receipt"?', options: ['r', 'c', 'p', 't'], answer: 2, vi: 'Chữ p câm.' }]),
  mk('c5', 4, 'Asking for Directions', '10 min', 'Excuse me, how do I get to the train station? Directions use imperatives like go straight and turn left.',
    [['straight', '/streɪt/', 'thẳng'], ['opposite', '/ˈɒpəzɪt/', 'đối diện'], ['intersection', '/ˌɪntəˈsekʃn/', 'ngã tư']],
    'Ask: "Excuse me, how do I get to…?" Give directions with "Go straight", "Turn left at…", "It\'s on your right".',
    'Bắt đầu bằng "Excuse me" để lịch sự khi hỏi người lạ.',
    [['Go straight and turn left at the intersection.', 'Đi thẳng rồi rẽ trái ở ngã tư.'], ["It's opposite the bank.", 'Nó ở đối diện ngân hàng.'], ['Is it far from here?', 'Nó có xa đây không?']],
    [{ q: '"Đối diện" in English is:', options: ['next to', 'opposite', 'behind', 'between'], answer: 1, vi: 'opposite = đối diện.' },
     { q: 'Excuse me, how do I ____ to the museum?', options: ['go', 'get', 'arrive', 'reach to'], answer: 1, vi: '"How do I get to…" là cấu trúc chuẩn.' }]),
  mk('c5', 5, 'Making Plans with Friends', '8 min', 'Are you free this Saturday? We are going to the beach. Let us make plans using the present continuous.',
    [['free', '/friː/', 'rảnh'], ['plan', '/plæn/', 'kế hoạch'], ['cancel', '/ˈkænsl/', 'huỷ']],
    'Use the present continuous for fixed plans: "I\'m meeting Lan tomorrow." Use "Are you free…?" to invite.',
    'Hiện tại tiếp diễn dùng cho kế hoạch đã sắp xếp trong tương lai gần.',
    [['Are you free on Saturday?', 'Thứ Bảy bạn rảnh không?'], ["I'm meeting my cousin tonight.", 'Tối nay tôi gặp em họ.'], ['Sorry, I have to cancel.', 'Xin lỗi, tôi phải huỷ.']],
    [{ q: 'I ____ my friends tomorrow at 7.', options: ['meet', 'am meeting', 'met', 'have met'], answer: 1, vi: 'Kế hoạch đã sắp xếp → hiện tại tiếp diễn.' },
     { q: '"Rảnh" in English:', options: ['busy', 'free', 'empty', 'open'], answer: 1, vi: 'free = rảnh rỗi.' }]),
  mk('c5', 6, 'Talking on the Phone', '9 min', 'Hello, this is Minh speaking. Could I speak to Ms Lan, please? Phone calls need special phrases.',
    [['hold on', '/həʊld ɒn/', 'giữ máy'], ['call back', '/kɔːl bæk/', 'gọi lại'], ['message', '/ˈmesɪdʒ/', 'lời nhắn']],
    'On the phone, say "This is Minh" (not "I am Minh"). Use "Could I speak to…?" and "Can I leave a message?".',
    'Khi nghe điện thoại, giới thiệu bằng "This is…" thay vì "I am…".',
    [['Hello, this is Minh speaking.', 'Alô, Minh nghe.'], ['Could you hold on a moment?', 'Bạn giữ máy một chút nhé?'], ["I'll call you back later.", 'Tôi sẽ gọi lại sau.']],
    [{ q: 'On the phone you say:', options: ['I am Minh.', 'This is Minh.', 'Here Minh.', 'Me Minh.'], answer: 1, vi: '"This is…" là cách giới thiệu qua điện thoại.' },
     { q: '"Giữ máy" means:', options: ['hang up', 'hold on', 'call back', 'pick up'], answer: 1, vi: 'hold on = giữ máy.' }]),

  /* c11 — English for Developers */
  mk('c11', 1, 'Daily Stand-up Updates', '10 min', 'Yesterday I finished the login page. Today I am working on the payment API. No blockers. That is a perfect stand-up update.',
    [['blocker', '/ˈblɒkər/', 'vấn đề cản trở'], ['finish', '/ˈfɪnɪʃ/', 'hoàn thành'], ['in progress', '/ɪn ˈprəʊɡres/', 'đang thực hiện']],
    'Structure: Yesterday I… / Today I\'m… / Blockers: … Keep it under 60 seconds.',
    'Stand-up gồm 3 phần: hôm qua làm gì, hôm nay làm gì, có vướng mắc gì không.',
    [['Yesterday I fixed two bugs in the checkout flow.', 'Hôm qua tôi sửa hai lỗi ở luồng thanh toán.'], ["Today I'm working on the search feature.", 'Hôm nay tôi làm tính năng tìm kiếm.'], ["I'm blocked by the API access.", 'Tôi đang bị vướng vì chưa có quyền truy cập API.']],
    [{ q: 'Today I ____ on the dashboard.', options: ['work', 'am working', 'worked', 'have work'], answer: 1, vi: 'Việc đang làm hôm nay → hiện tại tiếp diễn.' },
     { q: '"Blocker" means:', options: ['người chặn', 'vấn đề cản trở công việc', 'tường lửa', 'lỗi chính tả'], answer: 1, vi: 'blocker = vấn đề khiến bạn không tiếp tục được.' }]),
  mk('c11', 2, 'Explaining a Bug', '12 min', 'When a user clicks submit twice, the order is created twice. Let us explain bugs clearly: steps, expected result and actual result.',
    [['reproduce', '/ˌriːprəˈdjuːs/', 'tái hiện (lỗi)'], ['expected', '/ɪkˈspektɪd/', 'mong đợi'], ['crash', '/kræʃ/', 'sập, treo']],
    'A good bug report: Steps to reproduce → Expected result → Actual result → Environment.',
    'Báo lỗi tốt cần có: các bước tái hiện, kết quả mong đợi, kết quả thực tế và môi trường.',
    [['I can reproduce it on Chrome only.', 'Tôi tái hiện được lỗi chỉ trên Chrome.'], ['Expected: the form shows an error.', 'Mong đợi: form hiển thị lỗi.'], ['Actual: the app crashes.', 'Thực tế: ứng dụng bị treo.']],
    [{ q: 'To make a bug happen again is to ____ it.', options: ['produce', 'reproduce', 'deploy', 'release'], answer: 1, vi: 'reproduce = tái hiện.' },
     { q: 'Which is NOT part of a bug report?', options: ['Steps to reproduce', 'Expected result', 'Your salary', 'Actual result'], answer: 2, vi: 'Lương không liên quan đến báo lỗi 😄' }]),
  mk('c11', 3, 'Code Review Comments', '11 min', 'Could we extract this into a helper function? Kind, specific review comments make teams better.',
    [['refactor', '/riːˈfæktər/', 'tái cấu trúc'], ['readable', '/ˈriːdəbl/', 'dễ đọc'], ['nitpick', '/ˈnɪtpɪk/', 'góp ý nhỏ, bắt bẻ']],
    'Use questions and "we" to sound collaborative: "Could we…?", "What do you think about…?". Mark small issues with "nit:".',
    'Dùng câu hỏi và "we" để góp ý nhẹ nhàng, tránh ra lệnh.',
    [['Could we rename this variable to make it more readable?', 'Mình đổi tên biến này cho dễ đọc hơn nhé?'], ['Nit: missing semicolon here.', 'Góp ý nhỏ: thiếu dấu chấm phẩy.'], ['Nice refactor! Much cleaner.', 'Tái cấu trúc hay lắm! Gọn hơn nhiều.']],
    [{ q: 'The most collaborative comment:', options: ['Fix this.', 'This is wrong.', 'Could we move this into a function?', 'Bad code.'], answer: 2, vi: 'Dạng câu hỏi với "we" nghe hợp tác hơn.' },
     { q: '"Readable" code is:', options: ['dễ đọc', 'chạy nhanh', 'có lỗi', 'bị xoá'], answer: 0, vi: 'readable = dễ đọc.' }]),
  mk('c11', 4, 'Commit Messages & Pull Requests', '9 min', 'Add retry logic for failed payments. Good commit messages use the imperative mood.',
    [['imperative', '/ɪmˈperətɪv/', 'mệnh lệnh'], ['summary', '/ˈsʌməri/', 'tóm tắt'], ['merge', '/mɜːdʒ/', 'hợp nhất']],
    'Write commit messages in the imperative: "Fix login bug", not "Fixed" or "Fixing". PR descriptions: What, Why, How to test.',
    'Commit message dùng động từ nguyên mẫu ở đầu câu, như đang ra lệnh.',
    [['Fix typo in README', 'Sửa lỗi chính tả trong README'], ['Add unit tests for the cart service', 'Thêm unit test cho cart service'], ['Please review and merge when ready.', 'Nhờ review và merge khi sẵn sàng.']],
    [{ q: 'Best commit message:', options: ['fixed bug', 'Fixing some stuff', 'Fix null error on profile page', 'I fix bug'], answer: 2, vi: 'Mệnh lệnh + cụ thể.' },
     { q: '"Merge" means:', options: ['hợp nhất', 'xoá', 'sao chép', 'tạm dừng'], answer: 0, vi: 'merge = hợp nhất nhánh code.' }]),
  mk('c11', 5, 'Talking to Clients About Requirements', '13 min', 'Just to clarify, do you want users to log in with Google as well? Clarifying questions prevent expensive mistakes.',
    [['clarify', '/ˈklærəfaɪ/', 'làm rõ'], ['requirement', '/rɪˈkwaɪəmənt/', 'yêu cầu'], ['scope', '/skəʊp/', 'phạm vi']],
    'Use "Just to clarify…", "So if I understand correctly…", "Is that in scope?" to confirm requirements.',
    'Luôn xác nhận lại yêu cầu bằng lời của mình để tránh hiểu nhầm.',
    [['Just to clarify, is the deadline Friday?', 'Cho tôi hỏi lại, hạn chót là thứ Sáu phải không?'], ['So if I understand correctly, you need an admin panel.', 'Nếu tôi hiểu đúng thì anh cần một trang quản trị.'], ['That feature is out of scope for this phase.', 'Tính năng đó nằm ngoài phạm vi giai đoạn này.']],
    [{ q: '"Làm rõ" in English:', options: ['clarify', 'deploy', 'merge', 'scope'], answer: 0, vi: 'clarify = làm rõ.' },
     { q: '"Out of scope" means:', options: ['quá hạn', 'ngoài phạm vi', 'hết ngân sách', 'đã xong'], answer: 1, vi: 'scope = phạm vi.' }]),
  mk('c11', 6, 'Estimating and Deadlines', '10 min', 'I estimate this will take about three days, including testing. Learn to talk about time and risk honestly.',
    [['estimate', '/ˈestɪmeɪt/', 'ước tính'], ['realistic', '/ˌriːəˈlɪstɪk/', 'thực tế'], ['buffer', '/ˈbʌfər/', 'thời gian dự phòng']],
    'Give ranges and assumptions: "Around 3 to 5 days, assuming the API is ready."',
    'Khi ước tính, nên đưa khoảng thời gian và nêu giả định.',
    [['It should take around two days.', 'Việc này mất khoảng hai ngày.'], ["That's not realistic for Friday.", 'Thứ Sáu thì không thực tế.'], ["Let's add a one-day buffer.", 'Thêm một ngày dự phòng nhé.']],
    [{ q: 'Best estimate:', options: ['Fast.', 'Maybe.', '3–5 days, assuming the design is final.', 'I do not know never.'], answer: 2, vi: 'Có khoảng thời gian và giả định rõ ràng.' },
     { q: '"Buffer" time is:', options: ['thời gian dự phòng', 'thời gian nghỉ trưa', 'thời gian họp', 'giờ tan làm'], answer: 0, vi: 'buffer = khoảng dự phòng.' }]),

  /* c14 — Interview English */
  mk('c14', 1, 'Tell Me About Yourself', '12 min', 'I am a front-end developer with four years of experience building e-commerce websites. Start your interview with a strong introduction.',
    [['background', '/ˈbækɡraʊnd/', 'lý lịch, nền tảng'], ['currently', '/ˈkʌrəntli/', 'hiện tại'], ['passionate', '/ˈpæʃənət/', 'đam mê']],
    'Use Present → Past → Future: what you do now, key experience, why you want this role. Keep it to 60–90 seconds.',
    'Trả lời theo trình tự: hiện tại → quá khứ → tương lai. Không kể lại toàn bộ CV.',
    [["I'm currently working as a QA engineer at a fintech company.", 'Hiện tôi là kỹ sư kiểm thử ở một công ty fintech.'], ['I have a background in marketing.', 'Tôi có nền tảng về marketing.'], ["I'm passionate about user experience.", 'Tôi đam mê trải nghiệm người dùng.']],
    [{ q: 'Best structure for "Tell me about yourself":', options: ['Childhood → school → hobbies', 'Present → past → future', 'Salary → benefits', 'Weaknesses first'], answer: 1, vi: 'Hiện tại → quá khứ → tương lai.' },
     { q: 'I ____ as a designer since 2021.', options: ['work', 'am working', 'have worked', 'worked'], answer: 2, vi: '"Since 2021" → hiện tại hoàn thành.' }]),
  mk('c14', 2, 'Strengths and Weaknesses', '11 min', 'My greatest strength is problem-solving. One weakness is public speaking, but I am improving by joining a speaking club.',
    [['strength', '/streŋθ/', 'điểm mạnh'], ['weakness', '/ˈwiːknəs/', 'điểm yếu'], ['detail-oriented', '/ˈdiːteɪl ˈɔːrientɪd/', 'chú ý chi tiết']],
    'For weaknesses, choose a real but non-critical one and explain how you are improving it.',
    'Nói điểm yếu thật nhưng không quá nghiêm trọng, và luôn kèm cách bạn đang cải thiện.',
    [['My greatest strength is that I learn fast.', 'Điểm mạnh lớn nhất của tôi là học nhanh.'], ["I'm very detail-oriented.", 'Tôi rất chú ý đến chi tiết.'], ["I'm working on my presentation skills.", 'Tôi đang cải thiện kỹ năng thuyết trình.']],
    [{ q: 'The "th" in "strength" is pronounced:', options: ['/t/', '/θ/', '/s/', '/d/'], answer: 1, vi: 'Âm /θ/: đặt đầu lưỡi giữa hai hàm răng.' },
     { q: 'A good weakness answer includes:', options: ['No weaknesses', 'A plan to improve', 'Blaming your boss', 'A long story'], answer: 1, vi: 'Luôn kèm kế hoạch cải thiện.' }]),
  mk('c14', 3, 'Behavioral Questions with STAR', '14 min', 'Tell me about a time you solved a difficult problem. Use the STAR method: Situation, Task, Action, Result.',
    [['situation', '/ˌsɪtʃuˈeɪʃn/', 'tình huống'], ['outcome', '/ˈaʊtkʌm/', 'kết quả'], ['handle', '/ˈhændl/', 'xử lý']],
    'STAR = Situation, Task, Action, Result. Spend most time on Action and give a measurable Result.',
    'Phương pháp STAR: Tình huống – Nhiệm vụ – Hành động – Kết quả. Nên có số liệu cụ thể ở phần kết quả.',
    [['Our release was delayed by two weeks.', 'Bản phát hành của chúng tôi bị trễ hai tuần.'], ['I organised daily check-ins with the team.', 'Tôi tổ chức họp nhanh hằng ngày với nhóm.'], ['As a result, we shipped on time.', 'Kết quả là chúng tôi giao đúng hạn.']],
    [{ q: 'What does the "A" in STAR stand for?', options: ['Answer', 'Action', 'Ability', 'Attitude'], answer: 1, vi: 'A = Action (hành động).' },
     { q: 'The strongest Result:', options: ['It was good.', 'Everyone was happy.', 'We reduced errors by 40%.', 'I finished.'], answer: 2, vi: 'Kết quả có số liệu thuyết phục hơn.' }]),
  mk('c14', 4, 'Talking About Salary', '10 min', 'Based on my research and experience, I am looking for a range of twenty-five to thirty million dong per month.',
    [['expectation', '/ˌekspekˈteɪʃn/', 'kỳ vọng'], ['range', '/reɪndʒ/', 'khoảng'], ['negotiable', '/nɪˈɡəʊʃiəbl/', 'có thể thương lượng']],
    'Give a range, mention research, and stay flexible: "I\'m open to discussing the full package."',
    'Đưa ra khoảng lương, dựa trên khảo sát thị trường và thể hiện sự linh hoạt.',
    [['My salary expectation is around 30 million VND.', 'Mức lương kỳ vọng của tôi khoảng 30 triệu.'], ['The salary is negotiable.', 'Mức lương có thể thương lượng.'], ["I'm open to discussing the full package.", 'Tôi sẵn sàng trao đổi toàn bộ chế độ đãi ngộ.']],
    [{ q: '"Có thể thương lượng" is:', options: ['negotiable', 'expected', 'fixed', 'paid'], answer: 0, vi: 'negotiable.' },
     { q: 'Best answer about salary:', options: ['As much as possible.', 'I do not care.', 'A range based on market research.', 'Whatever.'], answer: 2, vi: 'Đưa khoảng lương dựa trên nghiên cứu.' }]),
  mk('c14', 5, 'Asking the Interviewer Questions', '8 min', 'What does a typical day look like for this role? Asking good questions shows real interest.',
    [['typical', '/ˈtɪpɪkl/', 'điển hình'], ['growth', '/ɡrəʊθ/', 'phát triển'], ['team culture', '/tiːm ˈkʌltʃər/', 'văn hoá nhóm']],
    'Ask about the role, team and growth. Avoid asking about salary or holidays first.',
    'Hỏi về công việc, đội nhóm và cơ hội phát triển. Tránh hỏi ngay về lương hay nghỉ phép.',
    [['What does a typical day look like?', 'Một ngày làm việc điển hình như thế nào?'], ['How do you measure success in this role?', 'Anh/chị đánh giá thành công ở vị trí này thế nào?'], ['What are the growth opportunities?', 'Có những cơ hội phát triển nào?']],
    [{ q: 'A good question to ask:', options: ['How many holidays?', 'Can I work 2 hours a day?', 'How do you measure success in this role?', 'Why is the office so far?'], answer: 2, vi: 'Thể hiện sự quan tâm đến công việc.' },
     { q: '"Typical" means:', options: ['điển hình', 'đặc biệt', 'hiếm', 'khó'], answer: 0, vi: 'typical = điển hình.' }]),
  mk('c14', 6, 'Following Up After the Interview', '7 min', 'Thank you for your time today. I really enjoyed learning about the team. A short follow-up email leaves a great impression.',
    [['appreciate', '/əˈpriːʃieɪt/', 'trân trọng'], ['follow up', '/ˈfɒləʊ ʌp/', 'liên hệ lại'], ['opportunity', '/ˌɒpəˈtjuːnəti/', 'cơ hội']],
    'Send a thank-you email within 24 hours. Mention one specific topic from the interview.',
    'Gửi email cảm ơn trong vòng 24 giờ, nhắc lại một chủ đề cụ thể trong buổi phỏng vấn.',
    [['Thank you for the opportunity to interview.', 'Cảm ơn anh/chị đã cho tôi cơ hội phỏng vấn.'], ['I appreciate your time.', 'Tôi trân trọng thời gian của anh/chị.'], ["I'm following up on my application.", 'Tôi liên hệ lại về hồ sơ ứng tuyển.']],
    [{ q: 'When to send a thank-you email?', options: ['After a month', 'Within 24 hours', 'Never', 'Before the interview'], answer: 1, vi: 'Trong vòng 24 giờ.' },
     { q: 'I ____ your time.', options: ['appreciate', 'appreciate for', 'am appreciate', 'appreciating'], answer: 0, vi: '"Appreciate" không đi với "for" khi có tân ngữ trực tiếp.' }]),

  /* c15 — IELTS */
  mk('c15', 1, 'IELTS Speaking Part 1', '12 min', 'Do you work or are you a student? Part 1 questions are about familiar topics. Extend your answers with a reason and an example.',
    [['extend', '/ɪkˈstend/', 'mở rộng'], ['familiar', '/fəˈmɪliər/', 'quen thuộc'], ['hometown', '/ˈhəʊmtaʊn/', 'quê nhà']],
    'Answer + Reason + Example. Two or three sentences per question is ideal.',
    'Công thức: Trả lời + Lý do + Ví dụ. Mỗi câu nên trả lời 2–3 câu.',
    [["I'm from Hue, a peaceful city in central Vietnam.", 'Tôi đến từ Huế, một thành phố yên bình ở miền Trung.'], ['I love it because the food is amazing.', 'Tôi yêu nó vì đồ ăn rất tuyệt.'], ['For example, bun bo Hue is famous nationwide.', 'Ví dụ, bún bò Huế nổi tiếng khắp cả nước.']],
    [{ q: 'An ideal Part 1 answer is:', options: ['Yes.', '2–3 sentences with a reason', 'A 5-minute speech', 'A memorised essay'], answer: 1, vi: 'Ngắn gọn nhưng có lý do.' },
     { q: '"Quê nhà" is:', options: ['homeland', 'hometown', 'homework', 'housework'], answer: 1, vi: 'hometown = quê nhà.' }]),
  mk('c15', 2, 'Speaking Part 2: The Cue Card', '15 min', 'Describe a place you would like to visit. You have one minute to prepare and must speak for up to two minutes.',
    [['cue card', '/kjuː kɑːd/', 'thẻ đề bài'], ['vivid', '/ˈvɪvɪd/', 'sống động'], ['breathtaking', '/ˈbreθteɪkɪŋ/', 'ngoạn mục']],
    'Use the 1-minute preparation to write keywords for each bullet point. Tell it like a story.',
    'Tận dụng 1 phút chuẩn bị để ghi từ khoá cho từng ý, kể như một câu chuyện.',
    [["I'd like to talk about Ha Giang.", 'Tôi muốn nói về Hà Giang.'], ['The mountain views are breathtaking.', 'Cảnh núi non thật ngoạn mục.'], ['I have a vivid memory of the trip.', 'Tôi có một kỷ niệm rất sống động về chuyến đi.']],
    [{ q: 'How long do you prepare in Part 2?', options: ['30 seconds', '1 minute', '5 minutes', 'No time'], answer: 1, vi: 'Bạn có 1 phút chuẩn bị.' },
     { q: '"Breathtaking" means:', options: ['khó thở', 'ngoạn mục', 'mệt mỏi', 'nhàm chán'], answer: 1, vi: 'breathtaking = đẹp ngoạn mục.' }]),
  mk('c15', 3, 'Writing Task 1: Describing Charts', '15 min', 'The number of tourists rose significantly between 2015 and 2019. Task 1 is about describing trends accurately.',
    [['rise', '/raɪz/', 'tăng'], ['decline', '/dɪˈklaɪn/', 'giảm'], ['fluctuate', '/ˈflʌktʃueɪt/', 'dao động']],
    'Write an overview of the main trends. Use verbs (rise, fall) and nouns (a rise, a fall) with adverbs (sharply, slightly).',
    'Luôn có đoạn tổng quan (overview). Dùng đa dạng động từ và danh từ chỉ xu hướng.',
    [['Sales rose sharply in 2020.', 'Doanh số tăng mạnh vào năm 2020.'], ['There was a slight decline in March.', 'Có sự giảm nhẹ vào tháng Ba.'], ['Prices fluctuated around $50.', 'Giá dao động quanh mức 50 đô.']],
    [{ q: 'Which is a noun?', options: ['rose', 'declined', 'a decline', 'sharply'], answer: 2, vi: '"a decline" là danh từ.' },
     { q: 'The most important paragraph in Task 1:', options: ['Overview', 'Opinion', 'Conclusion with advice', 'Personal story'], answer: 0, vi: 'Overview quyết định band Task Achievement.' }]),
  mk('c15', 4, 'Writing Task 2: Opinion Essays', '16 min', 'Some people believe university should be free. To what extent do you agree? A clear position is essential.',
    [['extent', '/ɪkˈstent/', 'mức độ'], ['furthermore', '/ˌfɜːðəˈmɔːr/', 'hơn nữa'], ['consequently', '/ˈkɒnsɪkwəntli/', 'do đó']],
    'State your position in the introduction and keep it consistent. Each body paragraph: one main idea + explanation + example.',
    'Nêu rõ quan điểm ngay ở mở bài và giữ nhất quán đến kết bài.',
    [['I completely agree with this statement.', 'Tôi hoàn toàn đồng ý với nhận định này.'], ['Furthermore, free education reduces inequality.', 'Hơn nữa, giáo dục miễn phí giảm bất bình đẳng.'], ['Consequently, more students can attend university.', 'Do đó, nhiều sinh viên có thể học đại học hơn.']],
    [{ q: '"Do đó" is:', options: ['however', 'consequently', 'although', 'despite'], answer: 1, vi: 'consequently = do đó.' },
     { q: 'Where should your opinion appear first?', options: ['Only conclusion', 'Introduction', 'Nowhere', 'Title'], answer: 1, vi: 'Mở bài.' }]),
  mk('c15', 5, 'Listening: Section Strategies', '12 min', 'Read the questions before the audio starts and predict the type of answer: a number, a name or a place.',
    [['predict', '/prɪˈdɪkt/', 'dự đoán'], ['distractor', '/dɪˈstræktər/', 'phương án gây nhiễu'], ['spelling', '/ˈspelɪŋ/', 'chính tả']],
    'Predict the answer type, underline keywords, and watch for distractors (speakers often correct themselves).',
    'Chú ý bẫy: người nói thường đưa thông tin rồi sửa lại ngay sau đó.',
    [['The meeting is on Tuesday — sorry, Wednesday.', 'Cuộc họp vào thứ Ba — à xin lỗi, thứ Tư.'], ['Can you spell your surname?', 'Bạn đánh vần họ của bạn được không?'], ['Predict whether the answer is a number.', 'Dự đoán xem đáp án có phải là số không.']],
    [{ q: '"The price is 20, no wait, 25 dollars." The answer is:', options: ['20', '25', '45', '5'], answer: 1, vi: 'Người nói tự sửa → 25.' },
     { q: 'A "distractor" is:', options: ['đáp án đúng', 'phương án gây nhiễu', 'giám thị', 'tai nghe'], answer: 1, vi: 'distractor = bẫy gây nhiễu.' }]),
  mk('c15', 6, 'Reading: Skimming & Scanning', '13 min', 'Skim to understand the main idea. Scan to find specific information like dates and names.',
    [['skim', '/skɪm/', 'đọc lướt ý chính'], ['scan', '/skæn/', 'đọc dò tìm'], ['paraphrase', '/ˈpærəfreɪz/', 'diễn đạt lại']],
    'Questions usually paraphrase the text. Look for synonyms, not identical words.',
    'Câu hỏi thường diễn đạt lại ý trong bài bằng từ đồng nghĩa, không lặp nguyên văn.',
    [['"Significant" may be paraphrased as "considerable".', '"Significant" có thể được diễn đạt lại là "considerable".'], ['Skim the first sentence of each paragraph.', 'Đọc lướt câu đầu của mỗi đoạn.'], ['Scan for numbers and capital letters.', 'Dò tìm số và chữ in hoa.']],
    [{ q: 'To find a specific date, you should:', options: ['skim', 'scan', 'translate every word', 'guess'], answer: 1, vi: 'scan = dò tìm thông tin cụ thể.' },
     { q: 'A paraphrase of "rapid" is:', options: ['slow', 'quick', 'late', 'rare'], answer: 1, vi: 'rapid ≈ quick.' }])
];

/* ---------------- Vocabulary (50 words) ---------------- */
DATA.vocab = [
  ['improve', '/ɪmˈpruːv/', 'verb', 'cải thiện', 'I want to improve my English.', 'Tôi muốn cải thiện tiếng Anh.', 'daily', 'A2'],
  ['confident', '/ˈkɒnfɪdənt/', 'adjective', 'tự tin', 'She feels confident when she speaks English.', 'Cô ấy thấy tự tin khi nói tiếng Anh.', 'daily', 'B1'],
  ['practice', '/ˈpræktɪs/', 'verb', 'luyện tập', 'I practice speaking every morning.', 'Tôi luyện nói mỗi sáng.', 'daily', 'A2'],
  ['habit', '/ˈhæbɪt/', 'noun', 'thói quen', 'Reading every day is a good habit.', 'Đọc sách mỗi ngày là thói quen tốt.', 'daily', 'A2'],
  ['schedule', '/ˈʃedjuːl/', 'noun', 'lịch trình', 'My schedule is busy this week.', 'Lịch của tôi tuần này kín.', 'daily', 'B1'],
  ['recommend', '/ˌrekəˈmend/', 'verb', 'gợi ý, đề xuất', 'Can you recommend a good restaurant?', 'Bạn gợi ý một nhà hàng ngon được không?', 'daily', 'B1'],
  ['appointment', '/əˈpɔɪntmənt/', 'noun', 'cuộc hẹn', 'I have a dentist appointment at 3 pm.', 'Tôi có hẹn nha sĩ lúc 3 giờ chiều.', 'daily', 'B1'],
  ['convenient', '/kənˈviːniənt/', 'adjective', 'thuận tiện', 'Is Friday convenient for you?', 'Thứ Sáu có tiện cho bạn không?', 'daily', 'B1'],
  ['neighbor', '/ˈneɪbər/', 'noun', 'hàng xóm', 'My neighbor is very friendly.', 'Hàng xóm của tôi rất thân thiện.', 'daily', 'A1'],
  ['delicious', '/dɪˈlɪʃəs/', 'adjective', 'ngon', 'This pho is delicious!', 'Món phở này ngon quá!', 'daily', 'A1'],
  ['grateful', '/ˈɡreɪtfl/', 'adjective', 'biết ơn', 'I am grateful for your help.', 'Tôi rất biết ơn sự giúp đỡ của bạn.', 'emotions', 'B1'],
  ['nervous', '/ˈnɜːvəs/', 'adjective', 'lo lắng, hồi hộp', 'I was nervous before the interview.', 'Tôi đã hồi hộp trước buổi phỏng vấn.', 'emotions', 'A2'],
  ['excited', '/ɪkˈsaɪtɪd/', 'adjective', 'hào hứng', 'We are excited about the trip.', 'Chúng tôi rất hào hứng với chuyến đi.', 'emotions', 'A2'],
  ['disappointed', '/ˌdɪsəˈpɔɪntɪd/', 'adjective', 'thất vọng', 'He was disappointed with the result.', 'Anh ấy thất vọng với kết quả.', 'emotions', 'B1'],
  ['embarrassed', '/ɪmˈbærəst/', 'adjective', 'xấu hổ, ngượng', 'I felt embarrassed when I forgot her name.', 'Tôi thấy ngượng khi quên tên cô ấy.', 'emotions', 'B1'],
  ['deadline', '/ˈdedlaɪn/', 'noun', 'hạn chót', 'The deadline is next Monday.', 'Hạn chót là thứ Hai tới.', 'work', 'B1'],
  ['colleague', '/ˈkɒliːɡ/', 'noun', 'đồng nghiệp', 'My colleague helped me with the report.', 'Đồng nghiệp đã giúp tôi làm báo cáo.', 'work', 'B1'],
  ['negotiate', '/nɪˈɡəʊʃieɪt/', 'verb', 'đàm phán', 'We need to negotiate the price.', 'Chúng ta cần đàm phán giá.', 'work', 'B2'],
  ['responsibility', '/rɪˌspɒnsəˈbɪləti/', 'noun', 'trách nhiệm', 'Testing is my responsibility.', 'Kiểm thử là trách nhiệm của tôi.', 'work', 'B1'],
  ['efficient', '/ɪˈfɪʃnt/', 'adjective', 'hiệu quả', 'This new process is more efficient.', 'Quy trình mới này hiệu quả hơn.', 'work', 'B2'],
  ['agenda', '/əˈdʒendə/', 'noun', 'chương trình họp', "Let's look at today's agenda.", 'Hãy xem chương trình họp hôm nay.', 'work', 'B1'],
  ['feedback', '/ˈfiːdbæk/', 'noun', 'phản hồi, góp ý', 'Thank you for your feedback.', 'Cảm ơn góp ý của bạn.', 'work', 'B1'],
  ['promotion', '/prəˈməʊʃn/', 'noun', 'sự thăng chức', 'She got a promotion last month.', 'Cô ấy được thăng chức tháng trước.', 'work', 'B1'],
  ['candidate', '/ˈkændɪdət/', 'noun', 'ứng viên', 'We interviewed five candidates.', 'Chúng tôi đã phỏng vấn năm ứng viên.', 'work', 'B1'],
  ['achievement', '/əˈtʃiːvmənt/', 'noun', 'thành tựu', 'Passing IELTS was a big achievement.', 'Đậu IELTS là một thành tựu lớn.', 'work', 'B1'],
  ['deploy', '/dɪˈplɔɪ/', 'verb', 'triển khai (phần mềm)', 'We deploy new code every Friday.', 'Chúng tôi triển khai code mới mỗi thứ Sáu.', 'tech', 'B2'],
  ['debug', '/ˌdiːˈbʌɡ/', 'verb', 'gỡ lỗi', 'I spent two hours trying to debug this function.', 'Tôi mất hai giờ gỡ lỗi hàm này.', 'tech', 'B1'],
  ['requirement', '/rɪˈkwaɪəmənt/', 'noun', 'yêu cầu', 'Please check the requirement again.', 'Vui lòng kiểm tra lại yêu cầu.', 'tech', 'B1'],
  ['implement', '/ˈɪmplɪment/', 'verb', 'thực hiện, triển khai', 'We will implement the new design next sprint.', 'Chúng tôi sẽ thực hiện thiết kế mới vào sprint sau.', 'tech', 'B2'],
  ['maintain', '/meɪnˈteɪn/', 'verb', 'duy trì, bảo trì', 'It is hard to maintain old code.', 'Rất khó bảo trì code cũ.', 'tech', 'B1'],
  ['scalable', '/ˈskeɪləbl/', 'adjective', 'có khả năng mở rộng', 'We need a scalable system.', 'Chúng ta cần một hệ thống có khả năng mở rộng.', 'tech', 'B2'],
  ['database', '/ˈdeɪtəbeɪs/', 'noun', 'cơ sở dữ liệu', 'The database is backed up every night.', 'Cơ sở dữ liệu được sao lưu mỗi đêm.', 'tech', 'B1'],
  ['release', '/rɪˈliːs/', 'verb', 'phát hành', 'We will release version 2.0 in May.', 'Chúng tôi sẽ phát hành phiên bản 2.0 vào tháng Năm.', 'tech', 'B1'],
  ['estimate', '/ˈestɪmeɪt/', 'verb', 'ước tính', 'Can you estimate how long it will take?', 'Bạn có thể ước tính mất bao lâu không?', 'tech', 'B1'],
  ['workaround', '/ˈwɜːkəraʊnd/', 'noun', 'giải pháp tạm thời', 'We found a workaround for the bug.', 'Chúng tôi tìm được cách xử lý tạm cho lỗi.', 'tech', 'B2'],
  ['itinerary', '/aɪˈtɪnərəri/', 'noun', 'lịch trình chuyến đi', 'Here is our itinerary for Da Lat.', 'Đây là lịch trình đi Đà Lạt của chúng ta.', 'travel', 'B2'],
  ['luggage', '/ˈlʌɡɪdʒ/', 'noun', 'hành lý', 'My luggage is too heavy.', 'Hành lý của tôi quá nặng.', 'travel', 'A2'],
  ['reservation', '/ˌrezəˈveɪʃn/', 'noun', 'sự đặt chỗ', 'I have a reservation under the name Linh.', 'Tôi có đặt chỗ tên Linh.', 'travel', 'B1'],
  ['destination', '/ˌdestɪˈneɪʃn/', 'noun', 'điểm đến', 'Phu Quoc is a popular destination.', 'Phú Quốc là điểm đến nổi tiếng.', 'travel', 'B1'],
  ['departure', '/dɪˈpɑːtʃər/', 'noun', 'sự khởi hành', 'The departure time is 8:45.', 'Giờ khởi hành là 8:45.', 'travel', 'B1'],
  ['souvenir', '/ˌsuːvəˈnɪər/', 'noun', 'quà lưu niệm', 'I bought a souvenir for my mom.', 'Tôi mua quà lưu niệm cho mẹ.', 'travel', 'A2'],
  ['significant', '/sɪɡˈnɪfɪkənt/', 'adjective', 'đáng kể', 'There was a significant increase in sales.', 'Doanh số đã tăng đáng kể.', 'ielts', 'B2'],
  ['consequence', '/ˈkɒnsɪkwəns/', 'noun', 'hậu quả', 'Pollution has serious consequences.', 'Ô nhiễm gây ra hậu quả nghiêm trọng.', 'ielts', 'B2'],
  ['environment', '/ɪnˈvaɪrənmənt/', 'noun', 'môi trường', 'We must protect the environment.', 'Chúng ta phải bảo vệ môi trường.', 'ielts', 'B1'],
  ['advantage', '/ədˈvɑːntɪdʒ/', 'noun', 'lợi thế, ưu điểm', 'One advantage of city life is convenience.', 'Một ưu điểm của cuộc sống thành thị là sự tiện lợi.', 'ielts', 'B1'],
  ['population', '/ˌpɒpjuˈleɪʃn/', 'noun', 'dân số', 'The population of Ho Chi Minh City is growing.', 'Dân số TP.HCM đang tăng.', 'ielts', 'B1'],
  ['tendency', '/ˈtendənsi/', 'noun', 'xu hướng', 'There is a tendency to work remotely.', 'Có xu hướng làm việc từ xa.', 'ielts', 'B2'],
  ['crucial', '/ˈkruːʃl/', 'adjective', 'then chốt, cực kỳ quan trọng', 'Sleep is crucial for learning.', 'Giấc ngủ cực kỳ quan trọng cho việc học.', 'ielts', 'B2'],
  ['fluctuate', '/ˈflʌktʃueɪt/', 'verb', 'dao động', 'Prices fluctuate during the year.', 'Giá cả dao động trong năm.', 'ielts', 'C1'],
  ['opportunity', '/ˌɒpəˈtjuːnəti/', 'noun', 'cơ hội', 'This job is a great opportunity.', 'Công việc này là một cơ hội tuyệt vời.', 'ielts', 'B1']
].map((w, i) => ({ id: 'w' + (i + 1), word: w[0], ipa: w[1], pos: w[2], vi: w[3], example: w[4], exVi: w[5], topic: w[6], level: w[7] }));
DATA.vocabTopics = { all: 'All topics', daily: 'Daily life', emotions: 'Emotions', work: 'Work', tech: 'Technology', travel: 'Travel', ielts: 'IELTS' };

/* ---------------- Grammar (7 topics, 20 questions) ---------------- */
DATA.grammar = [
  { id: 'tenses', name: 'Tenses', emoji: '⏳', title: 'Present Perfect', formula: 'S + have/has + V3 (past participle)',
    example: 'I have worked here for three years.', exampleVi: 'Tôi đã làm việc ở đây được ba năm.',
    en: 'Use the present perfect for actions that started in the past and continue now, or for life experiences without a specific time.',
    vi: 'Thì hiện tại hoàn thành được sử dụng để nói về hành động bắt đầu trong quá khứ và vẫn liên quan đến hiện tại.',
    tip: 'Dùng "for" + khoảng thời gian (for 3 years), "since" + mốc thời gian (since 2020).',
    examples: [['She has lived in Hanoi since 2019.', 'Cô ấy sống ở Hà Nội từ năm 2019.'], ["I've never been to Europe.", 'Tôi chưa bao giờ đến châu Âu.']],
    questions: [
      { q: 'I ____ English for five years.', options: ['learn', 'learned', 'have learned', 'am learning'], answer: 2, vi: '"For five years" + vẫn còn học → hiện tại hoàn thành.' },
      { q: 'They ____ in Da Nang since 2020.', options: ['live', 'have lived', 'lived', 'are live'], answer: 1, vi: '"Since 2020" là dấu hiệu của hiện tại hoàn thành.' },
      { q: 'I ____ my keys. I can\'t find them!', options: ['lose', 'have lost', 'am losing', 'loses'], answer: 1, vi: 'Hành động quá khứ có kết quả ở hiện tại.' },
      { q: 'She ____ to the gym yesterday.', options: ['has gone', 'went', 'goes', 'has been going'], answer: 1, vi: '"Yesterday" là thời điểm xác định → quá khứ đơn.' }] },
  { id: 'articles', name: 'Articles', emoji: '🅰️', title: 'A, An, The', formula: 'a + consonant sound, an + vowel sound, the + specific thing',
    example: 'I bought a book. The book is about AI.', exampleVi: 'Tôi mua một cuốn sách. Cuốn sách đó nói về AI.',
    en: 'Use a/an for something mentioned for the first time, and "the" when the listener knows which one you mean.',
    vi: 'Dùng "a/an" khi nhắc đến lần đầu, "the" khi người nghe đã biết đó là vật nào. Chọn a/an theo ÂM, không theo chữ cái.',
    tip: '"an hour" (h câm), "a university" (/juː/ là phụ âm).',
    examples: [['She is an engineer.', 'Cô ấy là một kỹ sư.'], ['The sun rises in the east.', 'Mặt trời mọc ở hướng đông.']],
    questions: [
      { q: 'I waited for ____ hour.', options: ['a', 'an', 'the', '—'], answer: 1, vi: '"Hour" bắt đầu bằng nguyên âm /aʊ/ (h câm) → an.' },
      { q: 'He studies at ____ university in Hue.', options: ['a', 'an', 'the', '—'], answer: 0, vi: '"University" bắt đầu bằng âm /j/ → a.' },
      { q: '____ Moon goes around the Earth.', options: ['A', 'An', 'The', '—'], answer: 2, vi: 'Vật duy nhất → the.' }] },
  { id: 'prepositions', name: 'Prepositions', emoji: '📍', title: 'In, On, At (time)', formula: 'at + time, on + day/date, in + month/year/season',
    example: 'The meeting is at 9 am on Monday.', exampleVi: 'Cuộc họp lúc 9 giờ sáng thứ Hai.',
    en: 'At for exact times, on for days and dates, in for longer periods like months, years and seasons.',
    vi: '"At" cho giờ cụ thể, "on" cho ngày/thứ, "in" cho tháng/năm/mùa. Nhớ: at night, in the morning.',
    tip: 'Nói "on the weekend" (Mỹ) hoặc "at the weekend" (Anh), không nói "in the weekend".',
    examples: [['I was born in 1998.', 'Tôi sinh năm 1998.'], ["Let's meet on Friday.", 'Gặp nhau vào thứ Sáu nhé.']],
    questions: [
      { q: 'My birthday is ____ July.', options: ['at', 'on', 'in', 'by'], answer: 2, vi: 'Tháng → in.' },
      { q: 'The class starts ____ 7:30.', options: ['at', 'on', 'in', 'for'], answer: 0, vi: 'Giờ cụ thể → at.' },
      { q: 'We have a party ____ Saturday.', options: ['at', 'on', 'in', 'to'], answer: 1, vi: 'Thứ trong tuần → on.' }] },
  { id: 'modals', name: 'Modal verbs', emoji: '🔑', title: 'Can, Should, Must', formula: 'Modal + V (bare infinitive)',
    example: 'You should practise speaking every day.', exampleVi: 'Bạn nên luyện nói mỗi ngày.',
    en: 'Modal verbs are followed by the base form of the verb, never "to" or -s.',
    vi: 'Sau động từ khuyết thiếu luôn là động từ nguyên mẫu không "to". Không nói "can able to" hay "should to go".',
    tip: '"Must" = bắt buộc (từ người nói), "have to" = bắt buộc (do quy định).',
    examples: [['Can you help me?', 'Bạn giúp tôi được không?'], ['You must wear a helmet.', 'Bạn phải đội mũ bảo hiểm.']],
    questions: [
      { q: 'You should ____ more water.', options: ['to drink', 'drinking', 'drink', 'drinks'], answer: 2, vi: 'Modal + V nguyên mẫu.' },
      { q: 'She ____ speak three languages.', options: ['can', 'cans', 'can to', 'is can'], answer: 0, vi: 'Modal không thêm -s.' },
      { q: 'Students ____ bring their ID card to the exam.', options: ['must', 'musts', 'must to', 'are must'], answer: 0, vi: 'Quy định bắt buộc → must.' }] },
  { id: 'conditionals', name: 'Conditionals', emoji: '🔀', title: 'First & Second Conditional', formula: 'If + present, will + V / If + past, would + V',
    example: 'If I had more time, I would learn Japanese.', exampleVi: 'Nếu có nhiều thời gian hơn, tôi sẽ học tiếng Nhật.',
    en: 'First conditional: real, possible future. Second conditional: unreal or imagined present situations.',
    vi: 'Câu điều kiện loại 1: có thể xảy ra. Loại 2: không có thật ở hiện tại. Với loại 2, dùng "were" cho mọi ngôi: If I were you…',
    tip: 'Không dùng "will" trong mệnh đề "if": If it rains (not "will rain").',
    examples: [['If it rains, we will stay home.', 'Nếu trời mưa, chúng ta sẽ ở nhà.'], ['If I were you, I would apply.', 'Nếu tôi là bạn, tôi sẽ nộp đơn.']],
    questions: [
      { q: 'If it ____ tomorrow, we will cancel the trip.', options: ['rains', 'will rain', 'rained', 'raining'], answer: 0, vi: 'Loại 1: If + hiện tại đơn.' },
      { q: 'If I ____ rich, I would travel the world.', options: ['am', 'was being', 'were', 'will be'], answer: 2, vi: 'Loại 2 dùng "were".' },
      { q: 'If you study hard, you ____ pass.', options: ['would', 'will', 'did', 'passed'], answer: 1, vi: 'Loại 1: will + V.' }] },
  { id: 'passive', name: 'Passive voice', emoji: '🔄', title: 'The Passive Voice', formula: 'S + be + V3 (+ by agent)',
    example: 'The report was written by Lan.', exampleVi: 'Bản báo cáo được viết bởi Lan.',
    en: 'Use the passive when the action is more important than who did it. Common in reports and technical writing.',
    vi: 'Câu bị động dùng khi hành động quan trọng hơn người thực hiện. Rất phổ biến trong văn bản kỹ thuật.',
    tip: 'Chia động từ "be" theo thì: is made, was made, has been made, will be made.',
    examples: [['English is spoken worldwide.', 'Tiếng Anh được nói trên toàn thế giới.'], ['The app was released in 2024.', 'Ứng dụng được phát hành năm 2024.']],
    questions: [
      { q: 'The bug ____ yesterday.', options: ['fixed', 'was fixed', 'is fix', 'has fix'], answer: 1, vi: 'Bị động quá khứ: was + V3.' },
      { q: 'Coffee ____ in the Central Highlands.', options: ['grows', 'is grown', 'grown', 'is grow'], answer: 1, vi: 'Bị động hiện tại: is + V3.' }] },
  { id: 'relative', name: 'Relative clauses', emoji: '🔗', title: 'Who, Which, That', formula: 'who (people), which (things), that (both, defining)',
    example: 'The teacher who helped me is from Canada.', exampleVi: 'Thầy giáo đã giúp tôi đến từ Canada.',
    en: 'Relative clauses add information about a noun. Use "who" for people and "which" for things.',
    vi: 'Mệnh đề quan hệ bổ sung thông tin cho danh từ: "who" cho người, "which" cho vật, "that" dùng được cho cả hai (mệnh đề xác định).',
    tip: 'Không dùng "that" sau dấu phẩy.',
    examples: [['This is the app that I use every day.', 'Đây là ứng dụng tôi dùng mỗi ngày.'], ['My sister, who lives in Hue, is a nurse.', 'Chị tôi, người sống ở Huế, là y tá.']],
    questions: [
      { q: 'The man ____ called you is my boss.', options: ['which', 'who', 'where', 'whose'], answer: 1, vi: 'Người → who.' },
      { q: 'The laptop ____ I bought is very fast.', options: ['who', 'which', 'whom', 'where'], answer: 1, vi: 'Vật → which/that.' }] }
];

/* ---------------- Listening (10 clips, 20 questions) ---------------- */
DATA.listening = [
  { id: 'ls1', title: "John's Saturday", level: 'A2', topic: 'Daily life',
    transcript: "Yesterday was Saturday, so John didn't go to work. In the morning, he called his friend Minh, and they had breakfast together at a small café near the river. After that, John visited Minh's new apartment and helped him move some furniture.",
    vi: 'Hôm qua là thứ Bảy nên John không đi làm. Buổi sáng, anh gọi cho bạn là Minh và họ ăn sáng cùng nhau ở một quán cà phê nhỏ gần sông. Sau đó, John đến thăm căn hộ mới của Minh và giúp bạn chuyển đồ đạc.',
    questions: [{ q: 'What did John do yesterday?', options: ['He went shopping.', 'He visited his friend.', 'He stayed home.', 'He went to work.'], answer: 1 },
                { q: 'Where did they have breakfast?', options: ['At home', 'At a café near the river', 'At a hotel', 'At the office'], answer: 1 }] },
  { id: 'ls2', title: 'Booking a Table', level: 'A2', topic: 'Restaurants',
    transcript: "Good evening, Lotus Restaurant. Yes, I'd like to book a table for four people on Friday at seven thirty. Certainly. Could I have your name, please? It's Hoa, H-O-A. Great, see you on Friday.",
    vi: 'Chào buổi tối, nhà hàng Lotus. Vâng, tôi muốn đặt bàn cho bốn người vào thứ Sáu lúc bảy giờ ba mươi. Dạ được. Cho tôi xin tên ạ? Tên tôi là Hoa, H-O-A. Tuyệt, hẹn gặp chị thứ Sáu.',
    questions: [{ q: 'How many people is the table for?', options: ['Two', 'Three', 'Four', 'Five'], answer: 2 },
                { q: 'What time is the booking?', options: ['7:00', '7:30', '8:00', '6:30'], answer: 1 }] },
  { id: 'ls3', title: 'Weather Forecast', level: 'B1', topic: 'Weather',
    transcript: "Here is the weather for Da Nang this weekend. Saturday will be sunny and hot, with temperatures reaching thirty-four degrees. However, on Sunday a storm is expected in the afternoon, so please bring an umbrella if you go out.",
    vi: 'Sau đây là thời tiết Đà Nẵng cuối tuần này. Thứ Bảy trời nắng nóng, nhiệt độ lên tới 34 độ. Tuy nhiên, chiều Chủ nhật dự kiến có bão, vì vậy hãy mang ô nếu bạn ra ngoài.',
    questions: [{ q: 'What will the weather be like on Saturday?', options: ['Rainy', 'Sunny and hot', 'Cold', 'Windy'], answer: 1 },
                { q: 'When is the storm expected?', options: ['Saturday morning', 'Saturday night', 'Sunday afternoon', 'Monday'], answer: 2 }] },
  { id: 'ls4', title: 'Stand-up Meeting', level: 'B1', topic: 'Work / IT',
    transcript: "Morning everyone. Yesterday I finished the login screen and fixed two bugs in the payment page. Today I'm going to write unit tests for the cart service. I'm blocked because I still don't have access to the staging server.",
    vi: 'Chào buổi sáng mọi người. Hôm qua tôi đã hoàn thành màn hình đăng nhập và sửa hai lỗi ở trang thanh toán. Hôm nay tôi sẽ viết unit test cho cart service. Tôi đang bị vướng vì vẫn chưa có quyền truy cập máy chủ staging.',
    questions: [{ q: 'What will the speaker do today?', options: ['Fix the login screen', 'Write unit tests', 'Deploy the app', 'Meet a client'], answer: 1 },
                { q: 'What is the blocker?', options: ['No laptop', 'No access to the staging server', 'Too many meetings', 'A sick colleague'], answer: 1 }] },
  { id: 'ls5', title: 'At the Airport', level: 'A2', topic: 'Travel',
    transcript: "Attention please. Vietnam Airlines flight VN two-one-five to Hanoi is now boarding at gate twelve. Passengers with small children may board first. Please have your boarding pass and ID ready.",
    vi: 'Xin chú ý. Chuyến bay VN215 của Vietnam Airlines đi Hà Nội đang lên máy bay tại cửa số 12. Hành khách có con nhỏ có thể lên trước. Vui lòng chuẩn bị sẵn thẻ lên máy bay và giấy tờ tùy thân.',
    questions: [{ q: 'Which gate is the flight boarding at?', options: ['Gate 2', 'Gate 12', 'Gate 20', 'Gate 15'], answer: 1 },
                { q: 'Who can board first?', options: ['Business passengers', 'Passengers with small children', 'Students', 'Crew only'], answer: 1 }] },
  { id: 'ls6', title: 'Job Interview', level: 'B1', topic: 'Interview',
    transcript: "So, tell me about yourself. Sure. I'm a marketing executive with three years of experience in digital campaigns. In my current role, I increased our social media followers by forty percent. I'm looking for a position where I can lead a small team.",
    vi: 'Vậy hãy giới thiệu về bản thân bạn. Vâng. Tôi là chuyên viên marketing với ba năm kinh nghiệm về chiến dịch kỹ thuật số. Ở vị trí hiện tại, tôi đã tăng 40% lượng người theo dõi mạng xã hội. Tôi đang tìm vị trí mà tôi có thể dẫn dắt một nhóm nhỏ.',
    questions: [{ q: 'How many years of experience does the candidate have?', options: ['One', 'Two', 'Three', 'Four'], answer: 2 },
                { q: 'What does the candidate want?', options: ['A higher salary', 'To lead a small team', 'To work from home', 'To change careers'], answer: 1 }] },
  { id: 'ls7', title: 'Doctor Appointment', level: 'B1', topic: 'Health',
    transcript: "Hello, I'd like to make an appointment with Doctor Tran. I've had a sore throat for three days. The earliest time is Thursday at ten a.m. That's fine. Please arrive fifteen minutes early to fill in a form.",
    vi: 'Xin chào, tôi muốn đặt lịch hẹn với bác sĩ Trần. Tôi bị đau họng ba ngày rồi. Giờ sớm nhất là 10 giờ sáng thứ Năm. Được ạ. Vui lòng đến sớm 15 phút để điền phiếu.',
    questions: [{ q: 'What is the problem?', options: ['A headache', 'A sore throat', 'A broken arm', 'A fever'], answer: 1 },
                { q: 'Why should the patient arrive early?', options: ['To pay', 'To fill in a form', 'To see a nurse', 'To park'], answer: 1 }] },
  { id: 'ls8', title: 'University Lecture', level: 'B2', topic: 'Academic',
    transcript: "Today we'll look at urbanisation in Southeast Asia. Between 2000 and 2020, the urban population of Vietnam rose significantly, from about twenty-four percent to nearly thirty-seven percent. The main driver was the growth of manufacturing jobs in cities.",
    vi: 'Hôm nay chúng ta sẽ tìm hiểu về đô thị hoá ở Đông Nam Á. Từ năm 2000 đến 2020, dân số thành thị của Việt Nam tăng đáng kể, từ khoảng 24% lên gần 37%. Động lực chính là sự tăng trưởng việc làm sản xuất ở thành phố.',
    questions: [{ q: 'What was the urban population in 2020?', options: ['About 24%', 'About 30%', 'Nearly 37%', 'Over 50%'], answer: 2 },
                { q: 'What was the main driver?', options: ['Tourism', 'Manufacturing jobs', 'Education', 'Agriculture'], answer: 1 }] },
  { id: 'ls9', title: 'Hotel Complaint', level: 'B1', topic: 'Travel',
    transcript: "Excuse me, I'm in room three-oh-eight. The air conditioner isn't working and it's really hot. I'm so sorry about that. We'll send someone right away, or we can move you to a room with a sea view.",
    vi: 'Xin lỗi, tôi ở phòng 308. Máy lạnh không hoạt động và trời rất nóng. Chúng tôi rất xin lỗi. Chúng tôi sẽ cử người lên ngay, hoặc có thể chuyển anh sang phòng hướng biển.',
    questions: [{ q: 'What is the problem?', options: ['No hot water', 'The air conditioner is broken', 'The room is noisy', 'The TV is broken'], answer: 1 },
                { q: 'What does the hotel offer?', options: ['A discount', 'A free dinner', 'A room with a sea view', 'A refund'], answer: 2 }] },
  { id: 'ls10', title: 'Online Course Advert', level: 'B2', topic: 'Education',
    transcript: "Want to speak English with confidence? Our twelve-week online course includes live classes twice a week and daily pronunciation practice. Sign up before the end of the month and get twenty percent off.",
    vi: 'Bạn muốn nói tiếng Anh tự tin? Khoá học trực tuyến 12 tuần của chúng tôi gồm lớp học trực tiếp hai lần mỗi tuần và luyện phát âm hằng ngày. Đăng ký trước cuối tháng để được giảm 20%.',
    questions: [{ q: 'How long is the course?', options: ['Two weeks', 'Eight weeks', 'Twelve weeks', 'One year'], answer: 2 },
                { q: 'How can you get a discount?', options: ['Bring a friend', 'Sign up before the end of the month', 'Pay in cash', 'Take a test'], answer: 1 }] }
];

/* ---------------- Speaking scenarios (10) ---------------- */
DATA.speakingCategories = ['All', 'Beginner', 'Daily Conversation', 'Travel', 'Workplace', 'Interview'];
DATA.scenarios = [
  { id: 's1', title: 'Ordering Coffee', category: 'Beginner', emoji: '☕', level: 'A1', desc: 'Order a drink at a café.', role: 'Barista',
    turns: [
      { ai: 'Hi! What would you like to order?', vi: 'Chào bạn! Bạn muốn gọi gì?', suggestions: ["I'd like a medium coffee, please.", 'Can I get an iced latte?'], hints: [['medium', 'cỡ vừa'], ['iced', 'đá']] },
      { ai: 'Sure! For here or to go?', vi: 'Được ạ! Uống tại chỗ hay mang đi?', suggestions: ['To go, please.', "For here, thanks."], hints: [['to go', 'mang đi'], ['for here', 'tại chỗ']] },
      { ai: "That's 45,000 dong. Would you like anything else?", vi: 'Của bạn 45.000 đồng. Bạn có muốn gọi thêm gì không?', suggestions: ["No, that's all. Thank you!", "Yes, a croissant, please."], hints: [["that's all", 'vậy thôi']] }] },
  { id: 's2', title: 'Introducing Yourself', category: 'Beginner', emoji: '👋', level: 'A1', desc: 'Meet a new friend.', role: 'New friend',
    turns: [
      { ai: "Hi, I'm Emma. What's your name?", vi: 'Chào, mình là Emma. Bạn tên gì?', suggestions: ["Nice to meet you, Emma. I'm Phuong.", "Hi Emma, my name is Phuong."], hints: [['nice to meet you', 'rất vui được gặp']] },
      { ai: 'Where are you from?', vi: 'Bạn đến từ đâu?', suggestions: ["I'm from Da Nang, in Vietnam.", 'I come from Hanoi.'], hints: [['come from', 'đến từ']] },
      { ai: 'Cool! What do you do?', vi: 'Hay quá! Bạn làm nghề gì?', suggestions: ["I'm a software developer.", "I'm a university student."], hints: [['developer', 'lập trình viên']] }] },
  { id: 's3', title: 'Making Weekend Plans', category: 'Daily Conversation', emoji: '📅', level: 'A2', desc: 'Invite a friend out.', role: 'Friend',
    turns: [
      { ai: 'Hey! Are you free this Saturday?', vi: 'Này! Thứ Bảy này bạn rảnh không?', suggestions: ["Yes, I'm free. What's the plan?", "I'm busy in the morning, but free after lunch."], hints: [['free', 'rảnh'], ['busy', 'bận']] },
      { ai: "How about going to the beach?", vi: 'Đi biển nhé?', suggestions: ['Sounds great! What time?', "I'd prefer to see a movie."], hints: [['sounds great', 'nghe hay đấy'], ['prefer', 'thích hơn']] },
      { ai: "Let's meet at 3 pm at My Khe Beach.", vi: 'Gặp nhau lúc 3 giờ chiều ở biển Mỹ Khê nhé.', suggestions: ['Perfect, see you there!', 'Can we make it 4 pm instead?'], hints: [['instead', 'thay vào đó']] }] },
  { id: 's4', title: 'Shopping for Clothes', category: 'Daily Conversation', emoji: '🛍️', level: 'A2', desc: 'Find the right size and price.', role: 'Shop assistant',
    turns: [
      { ai: 'Hello! Can I help you find something?', vi: 'Xin chào! Tôi giúp gì được cho bạn?', suggestions: ["I'm looking for a white shirt.", "I'm just looking, thanks."], hints: [['looking for', 'đang tìm']] },
      { ai: 'What size do you wear?', vi: 'Bạn mặc cỡ nào?', suggestions: ['Medium, please.', "I'm not sure. Can I try it on?"], hints: [['try on', 'mặc thử']] },
      { ai: "It's 350,000 dong, but there's 20% off today.", vi: 'Giá 350.000 đồng nhưng hôm nay giảm 20%.', suggestions: ["Great, I'll take it.", 'Do you have it in blue?'], hints: [["I'll take it", 'tôi lấy cái này']] }] },
  { id: 's5', title: 'Asking for Directions', category: 'Travel', emoji: '🗺️', level: 'A2', desc: 'Find your way around a city.', role: 'Local',
    turns: [
      { ai: 'You look lost. Can I help?', vi: 'Trông bạn có vẻ lạc đường. Tôi giúp nhé?', suggestions: ['Yes, how do I get to the train station?', 'Excuse me, where is the nearest ATM?'], hints: [['nearest', 'gần nhất']] },
      { ai: 'Go straight and turn left at the second traffic light.', vi: 'Đi thẳng rồi rẽ trái ở đèn giao thông thứ hai.', suggestions: ['Is it far from here?', 'Could you say that again, please?'], hints: [['far', 'xa'], ['say that again', 'nói lại']] },
      { ai: "It's about a ten-minute walk.", vi: 'Khoảng mười phút đi bộ.', suggestions: ['Thank you so much!', 'Great, thanks for your help.'], hints: [['walk', 'đi bộ']] }] },
  { id: 's6', title: 'Checking in at a Hotel', category: 'Travel', emoji: '🏨', level: 'A2', desc: 'Check in and ask about services.', role: 'Receptionist',
    turns: [
      { ai: 'Good evening! Do you have a reservation?', vi: 'Chào buổi tối! Anh/chị có đặt phòng trước không?', suggestions: ['Yes, under the name Linh Tran.', "Yes, I booked online."], hints: [['reservation', 'đặt phòng'], ['under the name', 'đặt tên']] },
      { ai: 'Could I see your passport, please?', vi: 'Cho tôi xem hộ chiếu được không?', suggestions: ['Sure, here you are.', 'Of course. Here it is.'], hints: [['here you are', 'của anh/chị đây']] },
      { ai: 'Your room is 512. Breakfast is from 6 to 10.', vi: 'Phòng của anh/chị là 512. Bữa sáng từ 6 đến 10 giờ.', suggestions: ['What time is check-out?', 'Is Wi-Fi free?'], hints: [['check-out', 'trả phòng']] }] },
  { id: 's7', title: 'Small Talk with a Colleague', category: 'Workplace', emoji: '🙂', level: 'B1', desc: 'Chat before a meeting starts.', role: 'Colleague',
    turns: [
      { ai: 'Morning! How was your weekend?', vi: 'Chào buổi sáng! Cuối tuần của bạn thế nào?', suggestions: ['It was great, I went hiking. How about you?', 'Pretty relaxing, I stayed home.'], hints: [['hiking', 'leo núi, đi bộ đường dài']] },
      { ai: 'Nice! Are you ready for the presentation?', vi: 'Hay đấy! Bạn chuẩn bị xong bài thuyết trình chưa?', suggestions: ['Almost. I just need to check the slides.', "Yes, I'm a bit nervous though."], hints: [['nervous', 'hồi hộp'], ['though', 'mặc dù vậy']] },
      { ai: "You'll do great. Want to grab lunch later?", vi: 'Bạn sẽ làm tốt thôi. Lát đi ăn trưa không?', suggestions: ["Sure, let's go at 12.", 'Sorry, I have a call at noon.'], hints: [['grab lunch', 'đi ăn trưa']] }] },
  { id: 's8', title: 'Daily Stand-up', category: 'Workplace', emoji: '🧑‍💻', level: 'B1', desc: 'Give your update to the team.', role: 'Scrum master',
    turns: [
      { ai: "Let's start. What did you work on yesterday?", vi: 'Bắt đầu nhé. Hôm qua bạn làm gì?', suggestions: ['Yesterday I finished the login page.', 'I fixed two bugs in the payment module.'], hints: [['finish', 'hoàn thành']] },
      { ai: 'Great. What are you working on today?', vi: 'Tốt. Hôm nay bạn làm gì?', suggestions: ["Today I'm writing unit tests.", "I'm starting the search feature."], hints: [['unit test', 'kiểm thử đơn vị']] },
      { ai: 'Any blockers?', vi: 'Có vướng mắc gì không?', suggestions: ['No blockers.', "Yes, I'm waiting for API access."], hints: [['blocker', 'vướng mắc']] }] },
  { id: 's9', title: 'Interview: Tell Me About Yourself', category: 'Interview', emoji: '💼', level: 'B1', desc: 'Answer the most common question.', role: 'Interviewer',
    turns: [
      { ai: 'Thanks for coming. Could you tell me about yourself?', vi: 'Cảm ơn bạn đã đến. Bạn giới thiệu về bản thân nhé?', suggestions: ["I'm a front-end developer with four years of experience.", "I recently graduated in Business Administration."], hints: [['experience', 'kinh nghiệm'], ['graduated', 'tốt nghiệp']] },
      { ai: 'Why do you want to work here?', vi: 'Tại sao bạn muốn làm việc ở đây?', suggestions: ["I admire your products and want to grow with your team.", 'Your company culture matches my values.'], hints: [['admire', 'ngưỡng mộ'], ['values', 'giá trị']] },
      { ai: 'Where do you see yourself in five years?', vi: 'Bạn thấy mình ở đâu sau 5 năm?', suggestions: ['I hope to lead a small team.', 'I want to become an expert in my field.'], hints: [['lead', 'dẫn dắt'], ['expert', 'chuyên gia']] }] },
  { id: 's10', title: 'Interview: Strengths', category: 'Interview', emoji: '⭐', level: 'B2', desc: 'Talk about strengths and weaknesses.', role: 'Interviewer',
    turns: [
      { ai: 'What is your greatest strength?', vi: 'Điểm mạnh lớn nhất của bạn là gì?', suggestions: ["I'm a fast learner and very detail-oriented.", 'My greatest strength is problem-solving.'], hints: [['detail-oriented', 'tỉ mỉ']] },
      { ai: 'And your biggest weakness?', vi: 'Còn điểm yếu lớn nhất?', suggestions: ["I sometimes take on too much, but I'm learning to delegate.", "Public speaking, so I joined a speaking club."], hints: [['delegate', 'giao việc']] },
      { ai: 'Do you have any questions for us?', vi: 'Bạn có câu hỏi nào cho chúng tôi không?', suggestions: ['What does a typical day look like?', 'How do you measure success in this role?'], hints: [['typical', 'điển hình']] }] }
];

/* ---------------- Pronunciation sentences ---------------- */
DATA.pronunciation = [
  { id: 'p1', text: 'I would like to improve my English.', level: 'A2', focus: '/t/ and /uː/', hard: ['to'],
    tips: { to: "Âm /t/ trong 'to' cần phát âm rõ hơn.", improve: "Nhấn trọng âm vào âm tiết thứ hai: im-PROVE.", english: "Âm /ʃ/ cuối từ: chu môi nhẹ và bật hơi." } },
  { id: 'p2', text: 'I think three things are important.', level: 'B1', focus: '/θ/', hard: ['think', 'three', 'things'],
    tips: { think: 'Âm /θ/ cần đặt đầu lưỡi nhẹ giữa hai hàm răng, không đọc thành /t/.', three: 'Âm /θr/: đặt lưỡi giữa răng rồi chuyển nhanh sang /r/.', things: 'Không đọc "tinh". Âm cuối /ŋz/ phải có /z/.' } },
  { id: 'p3', text: 'She sells seashells by the seashore.', level: 'B1', focus: '/s/ vs /ʃ/', hard: ['seashells', 'seashore'],
    tips: { sells: '/s/: đặt lưỡi sau răng trên, không chu môi.', seashells: 'Phân biệt /s/ và /ʃ/: /ʃ/ cần chu môi như "suỵt".', seashore: '/ʃɔː/: chu môi, âm dài.' } },
  { id: 'p4', text: 'Could you please send me the file?', level: 'A2', focus: 'Final sounds', hard: ['send', 'file'],
    tips: { send: 'Đừng bỏ âm cuối /d/ trong "send".', file: 'Âm /l/ cuối: đặt lưỡi lên chân răng trên.', could: 'Chữ "l" trong "could" là âm câm.' } },
  { id: 'p5', text: 'The weather is very nice today.', level: 'A1', focus: '/ð/ and /v/', hard: ['the', 'weather', 'very'],
    tips: { the: 'Âm /ð/: lưỡi giữa hai răng và rung dây thanh, không đọc thành /d/.', weather: '/ˈweðər/: âm /ð/ ở giữa từ.', very: 'Âm /v/: răng trên chạm môi dưới, không đọc thành /b/ hay /d/.' } },
  { id: 'p6', text: 'I usually walk to work.', level: 'A2', focus: '/ʒ/ and /w/', hard: ['usually', 'walk', 'work'],
    tips: { usually: '/ˈjuːʒuəli/: âm /ʒ/ như trong "television".', walk: 'Chữ "l" câm: /wɔːk/.', work: '/wɜːk/: âm /ɜː/ giữa miệng, khác với "walk".' } },
  { id: 'p7', text: 'Let me check the schedule for next week.', level: 'B1', focus: 'Consonant clusters', hard: ['schedule', 'next'],
    tips: { schedule: 'Anh-Mỹ: /ˈskedʒuːl/, Anh-Anh: /ˈʃedjuːl/.', next: 'Cụm /kst/ ở cuối: đọc đủ cả ba âm.', check: '/tʃ/ đầu từ bật hơi mạnh.' } },
  { id: 'p8', text: 'Thank you for your help yesterday.', level: 'A1', focus: '/θ/ and /j/', hard: ['thank', 'yesterday'],
    tips: { thank: 'Âm /θ/: đầu lưỡi giữa hai hàm răng, thổi hơi nhẹ.', yesterday: 'Âm /j/ đầu từ như "d" nhẹ của tiếng Việt miền Nam.', help: 'Đọc rõ âm cuối /lp/.' } },
  { id: 'p9', text: 'Our team released a new version last month.', level: 'B2', focus: 'Past -ed and /ʒ/', hard: ['released', 'version', 'month'],
    tips: { released: 'Đuôi -ed sau /s/ đọc là /t/: /rɪˈliːst/.', version: '/ˈvɜːʒn/: âm /ʒ/ ở giữa.', month: 'Âm /θ/ cuối từ, không đọc thành "mon".' } },
  { id: 'p10', text: 'Practice makes perfect.', level: 'A2', focus: 'Stress', hard: ['practice', 'perfect'],
    tips: { practice: 'Trọng âm đầu: PRAC-tice.', perfect: 'Tính từ: PER-fect. Đọc rõ cụm /kt/ cuối.', makes: 'Âm cuối /ks/ cần rõ.' } }
];

/* ---------------- Teachers (10) ---------------- */
DATA.teachers = [
  { id: 't1', name: 'Sarah Johnson', country: 'United States', flag: '🇺🇸', rating: 4.9, classes: 1250, spec: 'English Communication', topics: ['Conversation', 'Pronunciation'], levels: ['A2', 'B1', 'B2'], price: 250000, hue: 230, years: 8,
    intro: 'Hi! I help Vietnamese learners stop translating in their heads and start speaking naturally. My classes are relaxed, practical and full of real conversation.',
    certs: ['CELTA', 'TESOL (240 hours)', 'BA in Communication — University of Oregon'], langs: 'English (native), Vietnamese (basic)',
    reviews: [{ name: 'Nguyen Thu Trang', rating: 5, text: 'Sarah is so patient. After 10 classes I can talk with foreign clients without panicking.' }, { name: 'Le Quoc Bao', rating: 5, text: 'Very clear pronunciation feedback. Highly recommend!' }, { name: 'Pham My Linh', rating: 4.8, text: 'Fun classes and useful phrases for daily life.' }],
    slots: { 1: ['08:00', '19:00', '20:00'], 2: ['19:00', '21:00'], 3: ['08:00', '19:00'], 4: ['20:00'], 5: ['19:00', '20:00'], 6: ['09:00', '10:00', '14:00'] } },
  { id: 't2', name: 'James Carter', country: 'United Kingdom', flag: '🇬🇧', rating: 4.9, classes: 2140, spec: 'IELTS & Business English', topics: ['IELTS', 'Business'], levels: ['B1', 'B2', 'C1'], price: 350000, hue: 265, years: 12,
    intro: 'Former IELTS examiner. I focus on exactly what raises your band score: structure, vocabulary range and fluency.',
    certs: ['DELTA', 'Former IELTS Examiner', 'MA in Applied Linguistics'], langs: 'English (native)',
    reviews: [{ name: 'Tran Minh Khoa', rating: 5, text: 'Went from 6.0 to 7.5 in speaking in two months.' }, { name: 'Vo Thanh Ha', rating: 4.9, text: 'Detailed writing feedback. Worth every dong.' }],
    slots: { 1: ['19:00', '20:00'], 3: ['19:00', '20:00'], 5: ['18:00'], 6: ['08:00', '09:00'], 0: ['09:00', '10:00'] } },
  { id: 't3', name: 'Emily Nguyen', country: 'Australia', flag: '🇦🇺', rating: 4.8, classes: 980, spec: 'Beginner English', topics: ['Beginner', 'Conversation'], levels: ['A1', 'A2'], price: 180000, hue: 145, years: 5,
    intro: 'Việt kiều Úc — I can explain in Vietnamese when you get stuck, so beginners never feel lost.',
    certs: ['TESOL', 'Bachelor of Education — Monash University'], langs: 'English (native), Vietnamese (fluent)',
    reviews: [{ name: 'Hoang Van Nam', rating: 5, text: 'Cô giải thích bằng tiếng Việt khi cần, rất dễ hiểu!' }, { name: 'Dang Thi Mai', rating: 4.7, text: 'Perfect for total beginners like me.' }],
    slots: { 0: ['19:00', '20:00'], 2: ['18:00', '19:00'], 4: ['18:00', '19:00'], 6: ['15:00', '16:00'] } },
  { id: 't4', name: 'Michael Brown', country: 'Canada', flag: '🇨🇦', rating: 4.7, classes: 1430, spec: 'English at Work & Meetings', topics: ['Business', 'Conversation'], levels: ['B1', 'B2'], price: 280000, hue: 215, years: 10,
    intro: 'Ten years coaching professionals at multinational companies in Ho Chi Minh City. Let us rehearse your real meetings.',
    certs: ['CELTA', 'Business English Certificate Trainer'], langs: 'English (native), French',
    reviews: [{ name: 'Bui Ngoc Anh', rating: 4.8, text: 'Practised my actual weekly meeting script. Game changer.' }, { name: 'Ngo Duc Huy', rating: 4.6, text: 'Practical and professional.' }],
    slots: { 1: ['07:00', '12:00'], 2: ['07:00', '12:00'], 4: ['12:00', '19:00'], 5: ['07:00'] } },
  { id: 't5', name: 'Olivia Smith', country: 'Australia', flag: '🇦🇺', rating: 4.9, classes: 1760, spec: 'Daily Conversation & Travel', topics: ['Conversation', 'Travel'], levels: ['A2', 'B1'], price: 220000, hue: 30, years: 7,
    intro: 'Traveller and storyteller. We will role-play airports, hotels, restaurants and making friends abroad.',
    certs: ['TESOL', 'TEFL (Young Learners)'], langs: 'English (native), Spanish',
    reviews: [{ name: 'Tran Bao Ngoc', rating: 5, text: 'I used every phrase on my trip to Singapore!' }, { name: 'Le Hoang Phuc', rating: 4.8, text: 'Always smiling and encouraging.' }],
    slots: { 0: ['10:00', '11:00'], 1: ['20:00'], 3: ['20:00', '21:00'], 5: ['20:00'], 6: ['10:00'] } },
  { id: 't6', name: 'Daniel Lee', country: 'United States', flag: '🇺🇸', rating: 4.8, classes: 890, spec: 'English for Developers', topics: ['IT', 'Interview'], levels: ['B1', 'B2'], price: 300000, hue: 175, years: 6,
    intro: 'Software engineer turned English coach. I prepare developers for stand-ups, code reviews and technical interviews.',
    certs: ['TESOL', 'BSc Computer Science — UC San Diego'], langs: 'English (native), Korean',
    reviews: [{ name: 'Nguyen Van Duc', rating: 5, text: 'Passed my interview with a Singapore company. Thank you Daniel!' }, { name: 'Pham Quang Vinh', rating: 4.7, text: 'Finally someone who understands dev life.' }],
    slots: { 1: ['21:00'], 2: ['21:00'], 3: ['21:00'], 6: ['14:00', '15:00', '16:00'] } },
  { id: 't7', name: 'Hannah Wilson', country: 'United Kingdom', flag: '🇬🇧', rating: 4.7, classes: 670, spec: 'Presentations & TOEFL', topics: ['Business', 'IELTS'], levels: ['B2', 'C1'], price: 320000, hue: 290, years: 9,
    intro: 'I coach confident, well-structured speaking for presentations and academic exams.',
    certs: ['CELTA', 'MA in TESOL — University of Leeds'], langs: 'English (native)',
    reviews: [{ name: 'Do Thi Huong', rating: 4.8, text: 'My conference presentation went so well.' }],
    slots: { 2: ['08:00', '09:00'], 4: ['08:00', '09:00'], 6: ['11:00'] } },
  { id: 't8', name: 'Ryan Miller', country: 'United States', flag: '🇺🇸', rating: 4.8, classes: 1120, spec: 'Interview English', topics: ['Interview', 'Business'], levels: ['B1', 'B2'], price: 270000, hue: 340, years: 8,
    intro: 'Ex-recruiter. I know what interviewers listen for. We will build your answers and practise until they feel natural.',
    certs: ['TESOL', 'Certified Career Coach'], langs: 'English (native)',
    reviews: [{ name: 'Vu Minh Chau', rating: 5, text: 'Mock interviews were exactly like the real one.' }, { name: 'Tran Thi Lan', rating: 4.6, text: 'Great STAR method practice.' }],
    slots: { 1: ['18:00', '19:00'], 3: ['18:00'], 5: ['18:00', '19:00'], 0: ['15:00'] } },
  { id: 't9', name: 'Chloe Tran', country: 'Vietnam', flag: '🇻🇳', rating: 4.9, classes: 2010, spec: 'Grammar & TOEIC', topics: ['Grammar', 'Beginner'], levels: ['A1', 'A2', 'B1'], price: 160000, hue: 160, years: 9,
    intro: 'TOEIC 990 and IELTS 8.5. Mình giúp bạn nắm vững ngữ pháp từ gốc, giải thích bằng tiếng Việt dễ hiểu.',
    certs: ['IELTS 8.5', 'TOEIC 990', 'MA in English Language Teaching — ULIS'], langs: 'Vietnamese (native), English (C2)',
    reviews: [{ name: 'Phan Anh Tuan', rating: 5, text: 'Ngữ pháp được hệ thống lại rất rõ ràng.' }, { name: 'Ly Thu Ha', rating: 4.9, text: 'TOEIC tăng 200 điểm sau 2 tháng!' }],
    slots: { 0: ['08:00', '09:00', '20:00'], 2: ['20:00'], 4: ['20:00'], 6: ['08:00', '20:00'] } },
  { id: 't10', name: 'David Thompson', country: 'New Zealand', flag: '🇳🇿', rating: 4.6, classes: 540, spec: 'Technical English', topics: ['IT', 'Pronunciation'], levels: ['B1', 'B2'], price: 260000, hue: 185, years: 4,
    intro: 'Engineer and teacher. I help technical professionals write and speak clearly about complex topics.',
    certs: ['TEFL', 'BEng Mechanical Engineering'], langs: 'English (native)',
    reviews: [{ name: 'Nguyen Hai Dang', rating: 4.6, text: 'Helped me write much clearer documentation.' }],
    slots: { 1: ['20:00'], 3: ['20:00'], 5: ['20:00'], 6: ['19:00'] } }
];
DATA.teacherTopics = ['Conversation', 'Pronunciation', 'IELTS', 'Business', 'IT', 'Interview', 'Travel', 'Grammar', 'Beginner'];

/* ---------------- Level test (16 questions) ---------------- */
DATA.levelTest = [
  { cat: 'Vocabulary', w: 1, q: 'Choose the word that means "hàng xóm".', options: ['friend', 'neighbor', 'teacher', 'cousin'], answer: 1 },
  { cat: 'Grammar', w: 1, q: 'She ____ a teacher.', options: ['are', 'is', 'am', 'be'], answer: 1 },
  { cat: 'Listening', w: 1, audio: 'My name is Linh and I am twenty-five years old.', q: 'How old is Linh?', options: ['15', '20', '25', '35'], answer: 2 },
  { cat: 'Reading', w: 1, passage: 'The shop opens at 8 am and closes at 9 pm every day except Sunday.', q: 'When is the shop closed?', options: ['Monday', 'Saturday', 'Sunday', 'Every evening'], answer: 2 },
  { cat: 'Vocabulary', w: 2, q: 'I was very ____ before my exam, so I couldn\'t sleep.', options: ['nervous', 'delicious', 'convenient', 'lazy'], answer: 0 },
  { cat: 'Grammar', w: 2, q: 'We ____ to the cinema last night.', options: ['go', 'goes', 'went', 'have gone'], answer: 2 },
  { cat: 'Listening', w: 2, audio: "I usually take the bus to work, but today I'm riding my motorbike because it isn't raining.", q: 'How is the speaker travelling today?', options: ['By bus', 'By motorbike', 'On foot', 'By car'], answer: 1 },
  { cat: 'Reading', w: 2, passage: 'Minh wanted to buy a laptop, but it was too expensive. Instead, he bought a tablet and saved the rest of his money.', q: 'Why didn\'t Minh buy the laptop?', options: ['It was broken', 'It was too expensive', 'He preferred phones', 'The shop was closed'], answer: 1 },
  { cat: 'Vocabulary', w: 3, q: 'The company had to ____ the contract with the new supplier.', options: ['negotiate', 'celebrate', 'decorate', 'imitate'], answer: 0 },
  { cat: 'Grammar', w: 3, q: 'I ____ here since 2021.', options: ['work', 'am working', 'have worked', 'worked'], answer: 2 },
  { cat: 'Listening', w: 3, audio: "The meeting was supposed to be on Tuesday, but the manager moved it to Thursday afternoon because of the client visit.", q: 'When is the meeting now?', options: ['Tuesday morning', 'Tuesday afternoon', 'Thursday afternoon', 'Friday'], answer: 2 },
  { cat: 'Reading', w: 3, passage: 'Although remote work offers flexibility, many employees report feeling isolated and find it harder to separate work from personal life.', q: 'What is a disadvantage of remote work mentioned?', options: ['Lower salary', 'Feeling isolated', 'Longer commutes', 'More meetings'], answer: 1 },
  { cat: 'Vocabulary', w: 4, q: 'Prices tend to ____ throughout the year depending on demand.', options: ['fluctuate', 'fabricate', 'illustrate', 'hesitate'], answer: 0 },
  { cat: 'Grammar', w: 4, q: 'If I ____ about the traffic, I would have left earlier.', options: ['knew', 'had known', 'have known', 'would know'], answer: 1 },
  { cat: 'Grammar', w: 5, q: 'Not only ____ late, but he also forgot the documents.', options: ['he arrived', 'did he arrive', 'he did arrive', 'arrived he'], answer: 1 },
  { cat: 'Reading', w: 5, passage: 'The findings, while preliminary, cast doubt on the long-held assumption that bilingualism delays cognitive decline.', q: 'What does the text suggest?', options: ['Bilingualism clearly prevents decline', 'The results are final', 'A common belief may be wrong', 'Researchers ignored bilingualism'], answer: 2 }
];
DATA.levelResults = {
  A1: { desc: 'You know some basic words. Build a strong foundation with everyday phrases and core sounds.', path: ['c1', 'c5'], skills: ['Beginner English', 'Daily Conversation', 'Pronunciation Practice'] },
  A2: { desc: 'You can handle simple daily situations. Next, grow your vocabulary and speak in longer sentences.', path: ['c2', 'c5'], skills: ['Daily Conversation', 'Vocabulary Builder', 'Pronunciation Practice'] },
  B1: { desc: 'You understand everyday English but need more practice with speaking and complex grammar.', path: ['c3', 'c11'], skills: ['Intermediate Speaking', 'Vocabulary Builder', 'Pronunciation Practice'] },
  B2: { desc: 'You communicate well in most situations. Focus on fluency, natural expressions and exam strategies.', path: ['c15', 'c12'], skills: ['IELTS Preparation', 'Business English', 'AI Writing Checker'] },
  C1: { desc: 'You use English flexibly and effectively. Polish nuance, idioms and academic writing.', path: ['c4', 'c15'], skills: ['Advanced English', 'IELTS Band 7.5+', 'Presentation English'] },
  C2: { desc: 'Near-native proficiency. Maintain your level with debates, advanced writing and live classes.', path: ['c4', 'c9'], skills: ['Advanced English', 'Presentation English', 'Live Classes'] }
};

/* ---------------- Gamification ---------------- */
DATA.xpLevels = [{ n: 1, name: 'Beginner', min: 0 }, { n: 2, name: 'Explorer', min: 500 }, { n: 3, name: 'Speaker', min: 1500 }, { n: 4, name: 'Communicator', min: 3500 }, { n: 5, name: 'Fluent', min: 7000 }];
DATA.achievements = [
  { id: 'a1', icon: '🌟', name: 'First Step', desc: 'Complete your first lesson', metric: 'lessons', target: 1 },
  { id: 'a2', icon: '🔥', name: '7 Day Streak', desc: 'Learn 7 days in a row', metric: 'streak', target: 7 },
  { id: 'a3', icon: '💪', name: '30 Day Streak', desc: 'Learn 30 days in a row', metric: 'streak', target: 30 },
  { id: 'a4', icon: '🎯', name: '100 Lessons', desc: 'Complete 100 lessons', metric: 'lessons', target: 100 },
  { id: 'a5', icon: '🗣', name: '50 Speaking Sessions', desc: 'Finish 50 speaking sessions', metric: 'speaking', target: 50 },
  { id: 'a6', icon: '📚', name: '1,000 Words', desc: 'Learn 1,000 words', metric: 'words', target: 1000 },
  { id: 'a7', icon: '🎙', name: 'Clear Speaker', desc: 'Score 95+ in pronunciation', metric: 'pronBest', target: 95 },
  { id: 'a8', icon: '🧠', name: 'Grammar Guru', desc: 'Answer 50 grammar questions correctly', metric: 'grammar', target: 50 },
  { id: 'a9', icon: '👩‍🏫', name: 'Class Act', desc: 'Book your first live class', metric: 'classes', target: 1 },
  { id: 'a10', icon: '🏆', name: 'English Master', desc: 'Reach Level 5 (Fluent)', metric: 'xp', target: 7000 }
];
DATA.leaderboard = [
  { name: 'Nguyen Minh', xp: 6820, hue: 210 }, { name: 'Tran An', xp: 5940, hue: 150 }, { name: 'Le Anh', xp: 4870, hue: 330 },
  { name: 'Pham Nam', xp: 3610, hue: 30 }, { name: 'Hoang Linh', xp: 2980, hue: 270 }, { name: 'Vo Bao Chau', xp: 1890, hue: 190 },
  { name: 'Dang Quoc Huy', xp: 1320, hue: 0 }, { name: 'Bui Thanh Tam', xp: 940, hue: 100 }
];
DATA.notifications = [
  { id: 'n1', icon: '🔔', text: 'Your daily goal is almost complete.', time: '10 min ago' },
  { id: 'n2', icon: '🔥', text: 'Your 12-day streak is active.', time: '1 hour ago' },
  { id: 'n3', icon: '🎯', text: 'You completed Intermediate Vocabulary.', time: '3 hours ago' },
  { id: 'n4', icon: '📚', text: 'New lesson available: Agreeing and Disagreeing.', time: 'Yesterday' },
  { id: 'n5', icon: '🏆', text: 'You moved up to #6 on the weekly leaderboard.', time: 'Yesterday' },
  { id: 'n6', icon: '🎙', text: 'New pronunciation drill: the /θ/ sound.', time: '2 days ago' },
  { id: 'n7', icon: '👩‍🏫', text: 'Sarah Johnson has new evening slots this week.', time: '2 days ago' },
  { id: 'n8', icon: '⚡', text: 'Double XP weekend starts Saturday.', time: '3 days ago' },
  { id: 'n9', icon: '📝', text: 'Your writing check report is ready.', time: '4 days ago' },
  { id: 'n10', icon: '🎁', text: 'Try Premium free for 7 days.', time: '1 week ago' }
];
DATA.plans = [
  { id: 'free', name: 'Free', monthly: 0, desc: 'Start learning with the basics.', features: ['3 lessons per day', 'Basic pronunciation check', '50 flashcards', 'Level test'] },
  { id: 'basic', name: 'Basic', monthly: 99000, desc: 'For steady daily learners.', features: ['Unlimited lessons', 'Full vocabulary builder', 'Grammar & listening', 'Progress reports'] },
  { id: 'premium', name: 'Premium', monthly: 199000, popular: true, desc: 'Our most popular plan.', features: ['Everything in Basic', 'AI Pronunciation Coach', 'AI Tutor & Writing Checker', 'All speaking scenarios'] },
  { id: 'pro', name: 'Pro', monthly: 399000, desc: 'With live teachers every month.', features: ['Everything in Premium', '4 live classes per month', 'IELTS / TOEIC courses', 'Personal study plan'] }
];

/* ---------------- Grammar rules for AI Tutor / Writing Checker / Speaking (mock AI) ---------------- */
const third = v => ({ have: 'has', do: 'does', go: 'goes' }[v.toLowerCase()] || (/(s|sh|ch|x|o)$/i.test(v) ? v + 'es' : /[^aeiou]y$/i.test(v) ? v.slice(0, -1) + 'ies' : v + 's'));
DATA.grammarRules = [
  { re: /\bvery like\b/gi, fix: 'really like', en: "Use 'really' instead of 'very' before the verb 'like'.", vi: "Không dùng 'very' trước động từ. Dùng 'really like' hoặc 'like … very much'." },
  { re: /\b(I|we|they|you) (?:am|are|'m|'re) agree\b/gi, fix: '$1 agree', en: "'Agree' is a verb, so don't use 'am/are' before it.", vi: "'Agree' là động từ, không dùng 'am/are' trước nó." },
  { re: /\bdiscuss about\b/gi, fix: 'discuss', en: "'Discuss' doesn't need 'about'.", vi: "Động từ 'discuss' không đi với 'about'." },
  { re: /(?<!\b(?:does|did|doesn't|didn't|can|will|would|should|could|must|may|might|to|let) )\b(he|she|it|everyone|everybody|the company|my (?:boss|friend|mother|father|brother|sister|manager|team|company)) (go|want|like|have|do|work|live|need|play|study|watch|help|make|take|know|think|look|start|finish|use|cost|mean|seem)\b/gi, fix: (m, s, v) => `${s} ${third(v)}`, en: 'With he / she / it, add -s or -es to the verb in the present simple.', vi: 'Chủ ngữ ngôi thứ ba số ít (he/she/it) thì động từ thêm -s/-es.' },
  { re: /\bhave went\b/gi, fix: 'have gone', en: "The past participle of 'go' is 'gone'.", vi: "Quá khứ phân từ của 'go' là 'gone', không phải 'went'." },
  { re: /\bpeople is\b/gi, fix: 'people are', en: "'People' is plural, so use 'are'.", vi: "'People' là danh từ số nhiều, dùng 'are'." },
  { re: /\bmake (my |the |our )?homework\b/gi, fix: 'do $1homework', en: "We 'do' homework, not 'make' homework.", vi: "Cụm đúng là 'do homework'." },
  { re: /\bsince (\d+|two|three|four|five|six|many) (years|months|weeks|days|hours)\b/gi, fix: 'for $1 $2', en: "Use 'for' with a period of time and 'since' with a starting point.", vi: "'For' + khoảng thời gian, 'since' + mốc thời gian." },
  { re: /\bmarried with\b/gi, fix: 'married to', en: "We say 'married to someone'.", vi: "Nói 'married to', không nói 'married with'." },
  { re: /\bexplain me\b/gi, fix: 'explain to me', en: "Say 'explain something to someone'.", vi: "Cấu trúc: explain something to someone." },
  { re: /\bI (?:am|'m) boring\b/gi, fix: "I'm bored", en: "'Boring' describes things; 'bored' describes how you feel.", vi: "'Boring' = gây chán, 'bored' = cảm thấy chán." },
  { re: /\bcan able to\b/gi, fix: 'can', en: "Use 'can' or 'be able to', not both.", vi: "Không dùng 'can' và 'able to' cùng lúc." },
  { re: /\bmore better\b/gi, fix: 'better', en: "'Better' is already comparative.", vi: "'Better' đã là so sánh hơn, không thêm 'more'." },
  { re: /\bin the weekend\b/gi, fix: 'on the weekend', en: "Say 'on the weekend' (US) or 'at the weekend' (UK).", vi: "Dùng 'on/at the weekend', không dùng 'in'." },
  { re: /\bI have (\d+|twenty|thirty) years old\b/gi, fix: 'I am $1 years old', en: "Use 'be' for age: I am 25 years old.", vi: "Nói tuổi dùng 'be', không dùng 'have'." },
  { re: /\blisten music\b/gi, fix: 'listen to music', en: "'Listen' needs 'to' before an object.", vi: "'Listen' cần 'to' trước tân ngữ." },
  { re: /\bborrow me\b/gi, fix: 'lend me', en: "You 'lend' something to someone; you 'borrow' something from someone.", vi: "'Lend' = cho mượn, 'borrow' = mượn." },
  { re: /\binformations\b/gi, fix: 'information', en: "'Information' is uncountable.", vi: "'Information' là danh từ không đếm được, không thêm -s." },
  { re: /\badvices\b/gi, fix: 'advice', en: "'Advice' is uncountable.", vi: "'Advice' không đếm được." },
  { re: /\bI very (\w+)\b/gi, fix: 'I really $1', en: "'Very' can't modify a verb. Use 'really'.", vi: "'Very' không bổ nghĩa cho động từ." },
  { re: /\bdidn't (went|saw|ate|came|bought)\b/gi, fix: (m, v) => `didn't ${{ went: 'go', saw: 'see', ate: 'eat', came: 'come', bought: 'buy' }[v.toLowerCase()]}`, en: "After 'didn't', use the base verb.", vi: "Sau 'didn't' dùng động từ nguyên mẫu." },
  { re: /(^|[.!?]\s+|\s)i(?=[\s',.!?]|$)/g, fix: '$1I', en: "Always write 'I' as a capital letter.", vi: "Đại từ 'I' luôn viết hoa." }
];
DATA.betterWords = { 'very good': 'excellent', 'very bad': 'terrible', 'very big': 'huge', 'very small': 'tiny', 'very important': 'crucial', 'very tired': 'exhausted', 'very happy': 'delighted', 'very difficult': 'challenging', 'very interesting': 'fascinating', 'a lot of': 'plenty of', 'good': 'great', 'bad': 'poor', 'big': 'significant', 'thing': 'aspect', 'get better': 'improve' };
DATA.naturalWords = { 'I am ': "I'm ", 'do not ': "don't ", 'does not ': "doesn't ", 'it is ': "it's ", 'cannot ': "can't ", 'I will ': "I'll ", 'we are ': "we're ", 'In my opinion, I think': 'I think', 'In my opinion I think': 'I think', 'purchase': 'buy', 'assist': 'help', 'commence': 'start', 'go back home': 'go home' };
